import '../entities/academic_calendar_event_entity.dart';
import '../entities/academic_year_config_entity.dart';
import '../repositories/academic_calendar_repository.dart';
import '../repositories/academic_year_config_repository.dart';

class SaveAcademicYearWizard {
  const SaveAcademicYearWizard(
    this._configRepository,
    this._calendarRepository,
  );

  final AcademicYearConfigRepository _configRepository;
  final AcademicCalendarRepository _calendarRepository;

  Future<void> call(AcademicYearConfigEntity config) async {
    await _configRepository.save(config);

    for (final vacation in config.vacations) {
      await _calendarRepository.saveEvent(
        AcademicCalendarEventEntity(
          id: 'wizard_vacation_${config.id}_${vacation.id}',
          title: vacation.title,
          description: 'Generated by Academic Year Wizard',
          type: AcademicCalendarEventType.vacation,
          audience: AcademicCalendarAudience.wholeSchool,
          startDate: vacation.startDate,
          endDate: vacation.endDate,
          isAllDay: true,
          startMinutes: null,
          endMinutes: null,
          classIds: const [],
          location: '',
          academicSession: config.academicSession,
          isActive: true,
          createdAt: config.createdAt,
          updatedAt: config.updatedAt,
        ),
      );
    }

    for (final window in config.examWindows) {
      await _calendarRepository.saveEvent(
        AcademicCalendarEventEntity(
          id: 'wizard_exam_${config.id}_${window.id}',
          title: window.title,
          description: 'Exam window generated by Academic Year Wizard',
          type: AcademicCalendarEventType.exam,
          audience: AcademicCalendarAudience.wholeSchool,
          startDate: window.startDate,
          endDate: window.endDate,
          isAllDay: true,
          startMinutes: null,
          endMinutes: null,
          classIds: const [],
          location: '',
          academicSession: config.academicSession,
          isActive: true,
          createdAt: config.createdAt,
          updatedAt: config.updatedAt,
        ),
      );
    }
  }
}
