$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = (Get-Location).Path
if (-not (Test-Path (Join-Path $root 'pubspec.yaml'))) {
    throw 'Run this script from the almustafa-connect-erp project root.'
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupRoot = Join-Path (Split-Path $root -Parent) "almustafa-connect-erp_backups/academic_calendar_phase4_integration_$stamp"

function Read-ProjectFile {
    param([Parameter(Mandatory = $true)][string]$RelativePath)
    $path = Join-Path $root $RelativePath
    if (-not (Test-Path $path)) {
        throw "Required file not found: $RelativePath"
    }
    return [IO.File]::ReadAllText($path).Replace("`r`n", "`n")
}

function Write-ProjectFile {
    param(
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [Parameter(Mandatory = $true)][string]$Content
    )
    $path = Join-Path $root $RelativePath
    New-Item -ItemType Directory -Path (Split-Path $path -Parent) -Force | Out-Null
    [IO.File]::WriteAllText($path, $Content, $utf8)
    Write-Host "Created/updated: $RelativePath" -ForegroundColor Green
}

function Backup-ProjectFile {
    param([Parameter(Mandatory = $true)][string]$RelativePath)
    $source = Join-Path $root $RelativePath
    if (-not (Test-Path $source)) { return }
    $destination = Join-Path $backupRoot $RelativePath
    New-Item -ItemType Directory -Path (Split-Path $destination -Parent) -Force | Out-Null
    Copy-Item $source $destination -Force
}

function Ensure-BeforeAnchor {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [Parameter(Mandatory = $true)][string]$UniqueMarker,
        [Parameter(Mandatory = $true)][string]$Anchor,
        [Parameter(Mandatory = $true)][string]$Block
    )
    if ($Content.Contains($UniqueMarker)) { return $Content }
    $index = $Content.IndexOf($Anchor)
    if ($index -lt 0) { throw "Integration anchor not found: $Anchor" }
    return $Content.Substring(0, $index) + $Block + $Content.Substring($index)
}

$payloads = @{
    'lib/features/academic_calendar/domain/services/academic_calendar_policy_service.dart' = 'aW1wb3J0ICcuLi9lbnRpdGllcy9hY2FkZW1pY19jYWxlbmRhcl9ldmVudF9lbnRpdHkuZGFydCc7CmltcG9ydCAnLi4vZW50aXRpZXMvYWNhZGVtaWNfeWVhcl9jb25maWdfZW50aXR5LmRhcnQnOwoKY2xhc3MgQWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uIHsKICBjb25zdCBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oewogICAgcmVxdWlyZWQgdGhpcy5hbGxvd2VkLAogICAgcmVxdWlyZWQgdGhpcy5tZXNzYWdlLAogICAgdGhpcy5zdWdnZXN0ZWREYXRlLAogIH0pOwoKICBmaW5hbCBib29sIGFsbG93ZWQ7CiAgZmluYWwgU3RyaW5nIG1lc3NhZ2U7CiAgZmluYWwgRGF0ZVRpbWU/IHN1Z2dlc3RlZERhdGU7Cn0KCmFic3RyYWN0IGNsYXNzIEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lTZXJ2aWNlIHsKICBGdXR1cmU8QWNhZGVtaWNZZWFyQ29uZmlnRW50aXR5Pz4gZ2V0Q29uZmlnKFN0cmluZyBhY2FkZW1pY1Nlc3Npb24pOwoKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZUF0dGVuZGFuY2VEYXRlKHsKICAgIHJlcXVpcmVkIFN0cmluZyBhY2FkZW1pY1Nlc3Npb24sCiAgICByZXF1aXJlZCBEYXRlVGltZSBkYXRlLAogIH0pOwoKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZVRpbWV0YWJsZURhdGUoewogICAgcmVxdWlyZWQgU3RyaW5nIGFjYWRlbWljU2Vzc2lvbiwKICAgIHJlcXVpcmVkIERhdGVUaW1lIGRhdGUsCiAgICByZXF1aXJlZCBib29sIHVzZXNaZXJvUGVyaW9kLAogIH0pOwoKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZUhvbWV3b3JrRHVlRGF0ZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZGF0ZSwKICB9KTsKCiAgRnV0dXJlPEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbj4gdmFsaWRhdGVFeGFtRGF0ZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZGF0ZSwKICB9KTsKCiAgRnV0dXJlPERhdGVUaW1lPiByZXNvbHZlRmVlR2VuZXJhdGlvbkRhdGUoewogICAgcmVxdWlyZWQgU3RyaW5nIGFjYWRlbWljU2Vzc2lvbiwKICAgIHJlcXVpcmVkIGludCBtb250aCwKICAgIHJlcXVpcmVkIGludCB5ZWFyLAogIH0pOwoKICBGdXR1cmU8RGF0ZVRpbWU+IHJlc29sdmVGZWVEdWVEYXRlKHsKICAgIHJlcXVpcmVkIFN0cmluZyBhY2FkZW1pY1Nlc3Npb24sCiAgICByZXF1aXJlZCBpbnQgbW9udGgsCiAgICByZXF1aXJlZCBpbnQgeWVhciwKICB9KTsKCiAgRnV0dXJlPERhdGVUaW1lPiBuZXh0V29ya2luZ0RheSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZnJvbSwKICB9KTsKCiAgRnV0dXJlPExpc3Q8QWNhZGVtaWNDYWxlbmRhckV2ZW50RW50aXR5Pj4gZ2V0VmlzaWJsZUV2ZW50cyh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgQWNhZGVtaWNDYWxlbmRhckF1ZGllbmNlIGF1ZGllbmNlLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgc3RhcnREYXRlLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZW5kRGF0ZSwKICAgIExpc3Q8U3RyaW5nPiBjbGFzc0lkcyA9IGNvbnN0IFtdLAogIH0pOwp9Cg=='
    'lib/features/academic_calendar/data/services/academic_calendar_policy_service_impl.dart' = 'aW1wb3J0ICcuLi8uLi9kb21haW4vZW50aXRpZXMvYWNhZGVtaWNfY2FsZW5kYXJfZXZlbnRfZW50aXR5LmRhcnQnOwppbXBvcnQgJy4uLy4uL2RvbWFpbi9lbnRpdGllcy9hY2FkZW1pY195ZWFyX2NvbmZpZ19lbnRpdHkuZGFydCc7CmltcG9ydCAnLi4vLi4vZG9tYWluL3JlcG9zaXRvcmllcy9hY2FkZW1pY19jYWxlbmRhcl9yZXBvc2l0b3J5LmRhcnQnOwppbXBvcnQgJy4uLy4uL2RvbWFpbi9yZXBvc2l0b3JpZXMvYWNhZGVtaWNfeWVhcl9jb25maWdfcmVwb3NpdG9yeS5kYXJ0JzsKaW1wb3J0ICcuLi8uLi9kb21haW4vc2VydmljZXMvYWNhZGVtaWNfY2FsZW5kYXJfcG9saWN5X3NlcnZpY2UuZGFydCc7CgpjbGFzcyBBY2FkZW1pY0NhbGVuZGFyUG9saWN5U2VydmljZUltcGwKICAgIGltcGxlbWVudHMgQWNhZGVtaWNDYWxlbmRhclBvbGljeVNlcnZpY2UgewogIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lTZXJ2aWNlSW1wbCgKICAgIHRoaXMuX2NvbmZpZ1JlcG9zaXRvcnksCiAgICB0aGlzLl9jYWxlbmRhclJlcG9zaXRvcnksCiAgKTsKCiAgZmluYWwgQWNhZGVtaWNZZWFyQ29uZmlnUmVwb3NpdG9yeSBfY29uZmlnUmVwb3NpdG9yeTsKICBmaW5hbCBBY2FkZW1pY0NhbGVuZGFyUmVwb3NpdG9yeSBfY2FsZW5kYXJSZXBvc2l0b3J5OwoKICBAb3ZlcnJpZGUKICBGdXR1cmU8QWNhZGVtaWNZZWFyQ29uZmlnRW50aXR5Pz4gZ2V0Q29uZmlnKAogICAgU3RyaW5nIGFjYWRlbWljU2Vzc2lvbiwKICApIHsKICAgIHJldHVybiBfY29uZmlnUmVwb3NpdG9yeS5nZXRCeVNlc3Npb24oYWNhZGVtaWNTZXNzaW9uKTsKICB9CgogIEBvdmVycmlkZQogIEZ1dHVyZTxBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24+IHZhbGlkYXRlQXR0ZW5kYW5jZURhdGUoewogICAgcmVxdWlyZWQgU3RyaW5nIGFjYWRlbWljU2Vzc2lvbiwKICAgIHJlcXVpcmVkIERhdGVUaW1lIGRhdGUsCiAgfSkgYXN5bmMgewogICAgZmluYWwgY29uZmlnID0gYXdhaXQgX3JlcXVpcmVkQ29uZmlnKGFjYWRlbWljU2Vzc2lvbik7CgogICAgaWYgKCFfaW5zaWRlU2Vzc2lvbihjb25maWcsIGRhdGUpKSB7CiAgICAgIHJldHVybiBjb25zdCBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oCiAgICAgICAgYWxsb3dlZDogZmFsc2UsCiAgICAgICAgbWVzc2FnZTogJ0F0dGVuZGFuY2UgZGF0ZSBpcyBvdXRzaWRlIHRoZSBhY2FkZW1pYyBzZXNzaW9uLicsCiAgICAgICk7CiAgICB9CgogICAgaWYgKCFjb25maWcud29ya2luZ1dlZWtkYXlzLmNvbnRhaW5zKGRhdGUud2Vla2RheSkpIHsKICAgICAgcmV0dXJuIEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnQXR0ZW5kYW5jZSBjYW5ub3QgYmUgbWFya2VkIG9uIGEgbm9uLXdvcmtpbmcgZGF5LicsCiAgICAgICAgc3VnZ2VzdGVkRGF0ZTogYXdhaXQgbmV4dFdvcmtpbmdEYXkoCiAgICAgICAgICBhY2FkZW1pY1Nlc3Npb246IGFjYWRlbWljU2Vzc2lvbiwKICAgICAgICAgIGZyb206IGRhdGUsCiAgICAgICAgKSwKICAgICAgKTsKICAgIH0KCiAgICBpZiAoY29uZmlnLmlzVmFjYXRpb25EYXRlKGRhdGUpIHx8CiAgICAgICAgYXdhaXQgX2lzSG9saWRheShhY2FkZW1pY1Nlc3Npb24sIGRhdGUpKSB7CiAgICAgIHJldHVybiBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oCiAgICAgICAgYWxsb3dlZDogZmFsc2UsCiAgICAgICAgbWVzc2FnZTogJ0F0dGVuZGFuY2UgY2Fubm90IGJlIG1hcmtlZCBvbiBhIGhvbGlkYXkgb3IgdmFjYXRpb24uJywKICAgICAgICBzdWdnZXN0ZWREYXRlOiBhd2FpdCBuZXh0V29ya2luZ0RheSgKICAgICAgICAgIGFjYWRlbWljU2Vzc2lvbjogYWNhZGVtaWNTZXNzaW9uLAogICAgICAgICAgZnJvbTogZGF0ZSwKICAgICAgICApLAogICAgICApOwogICAgfQoKICAgIHJldHVybiBjb25zdCBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oCiAgICAgIGFsbG93ZWQ6IHRydWUsCiAgICAgIG1lc3NhZ2U6ICdBdHRlbmRhbmNlIGRhdGUgaXMgdmFsaWQuJywKICAgICk7CiAgfQoKICBAb3ZlcnJpZGUKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZVRpbWV0YWJsZURhdGUoewogICAgcmVxdWlyZWQgU3RyaW5nIGFjYWRlbWljU2Vzc2lvbiwKICAgIHJlcXVpcmVkIERhdGVUaW1lIGRhdGUsCiAgICByZXF1aXJlZCBib29sIHVzZXNaZXJvUGVyaW9kLAogIH0pIGFzeW5jIHsKICAgIGZpbmFsIGNvbmZpZyA9IGF3YWl0IF9yZXF1aXJlZENvbmZpZyhhY2FkZW1pY1Nlc3Npb24pOwogICAgZmluYWwgYXR0ZW5kYW5jZSA9IGF3YWl0IHZhbGlkYXRlQXR0ZW5kYW5jZURhdGUoCiAgICAgIGFjYWRlbWljU2Vzc2lvbjogYWNhZGVtaWNTZXNzaW9uLAogICAgICBkYXRlOiBkYXRlLAogICAgKTsKCiAgICBpZiAoIWF0dGVuZGFuY2UuYWxsb3dlZCkgewogICAgICByZXR1cm4gQWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uKAogICAgICAgIGFsbG93ZWQ6IGZhbHNlLAogICAgICAgIG1lc3NhZ2U6IGF0dGVuZGFuY2UubWVzc2FnZS5yZXBsYWNlRmlyc3QoCiAgICAgICAgICAnQXR0ZW5kYW5jZScsCiAgICAgICAgICAnVGltZXRhYmxlJywKICAgICAgICApLAogICAgICAgIHN1Z2dlc3RlZERhdGU6IGF0dGVuZGFuY2Uuc3VnZ2VzdGVkRGF0ZSwKICAgICAgKTsKICAgIH0KCiAgICBpZiAoZGF0ZS53ZWVrZGF5ID09IERhdGVUaW1lLnNhdHVyZGF5ICYmCiAgICAgICAgIWNvbmZpZy5zYXR1cmRheVRpbWV0YWJsZUFsbG93ZWQpIHsKICAgICAgcmV0dXJuIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnU2F0dXJkYXkgdGltZXRhYmxlIGlzIGRpc2FibGVkIGluIEFjYWRlbWljIFllYXIgV2l6YXJkLicsCiAgICAgICk7CiAgICB9CgogICAgaWYgKHVzZXNaZXJvUGVyaW9kICYmICFjb25maWcuemVyb1BlcmlvZEFsbG93ZWQpIHsKICAgICAgcmV0dXJuIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnWmVybyBwZXJpb2QgaXMgZGlzYWJsZWQgaW4gQWNhZGVtaWMgWWVhciBXaXphcmQuJywKICAgICAgKTsKICAgIH0KCiAgICByZXR1cm4gY29uc3QgQWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uKAogICAgICBhbGxvd2VkOiB0cnVlLAogICAgICBtZXNzYWdlOiAnVGltZXRhYmxlIGRhdGUgaXMgdmFsaWQuJywKICAgICk7CiAgfQoKICBAb3ZlcnJpZGUKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZUhvbWV3b3JrRHVlRGF0ZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZGF0ZSwKICB9KSBhc3luYyB7CiAgICBmaW5hbCBjb25maWcgPSBhd2FpdCBfcmVxdWlyZWRDb25maWcoYWNhZGVtaWNTZXNzaW9uKTsKCiAgICBpZiAoIV9pbnNpZGVTZXNzaW9uKGNvbmZpZywgZGF0ZSkpIHsKICAgICAgcmV0dXJuIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnSG9tZXdvcmsgZHVlIGRhdGUgaXMgb3V0c2lkZSB0aGUgYWNhZGVtaWMgc2Vzc2lvbi4nLAogICAgICApOwogICAgfQoKICAgIGlmIChjb25maWcuaXNWYWNhdGlvbkRhdGUoZGF0ZSkgJiYKICAgICAgICAhY29uZmlnLmhvbWV3b3JrQWxsb3dlZEluVmFjYXRpb25zKSB7CiAgICAgIHJldHVybiBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oCiAgICAgICAgYWxsb3dlZDogZmFsc2UsCiAgICAgICAgbWVzc2FnZTogJ0hvbWV3b3JrIGlzIG5vdCBhbGxvd2VkIGR1cmluZyB2YWNhdGlvbnMuJywKICAgICAgICBzdWdnZXN0ZWREYXRlOiBhd2FpdCBuZXh0V29ya2luZ0RheSgKICAgICAgICAgIGFjYWRlbWljU2Vzc2lvbjogYWNhZGVtaWNTZXNzaW9uLAogICAgICAgICAgZnJvbTogZGF0ZSwKICAgICAgICApLAogICAgICApOwogICAgfQoKICAgIGlmIChhd2FpdCBfaXNIb2xpZGF5KGFjYWRlbWljU2Vzc2lvbiwgZGF0ZSkgJiYKICAgICAgICAhY29uZmlnLmhvbWV3b3JrQWxsb3dlZE9uSG9saWRheXMpIHsKICAgICAgcmV0dXJuIEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnSG9tZXdvcmsgaXMgbm90IGFsbG93ZWQgb24gaG9saWRheXMuJywKICAgICAgICBzdWdnZXN0ZWREYXRlOiBhd2FpdCBuZXh0V29ya2luZ0RheSgKICAgICAgICAgIGFjYWRlbWljU2Vzc2lvbjogYWNhZGVtaWNTZXNzaW9uLAogICAgICAgICAgZnJvbTogZGF0ZSwKICAgICAgICApLAogICAgICApOwogICAgfQoKICAgIGlmICghY29uZmlnLmhvbWV3b3JrQWxsb3dlZFdlZWtkYXlzLmNvbnRhaW5zKGRhdGUud2Vla2RheSkpIHsKICAgICAgcmV0dXJuIEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnSG9tZXdvcmsgaXMgbm90IGFsbG93ZWQgb24gdGhpcyB3ZWVrZGF5LicsCiAgICAgICAgc3VnZ2VzdGVkRGF0ZTogYXdhaXQgbmV4dFdvcmtpbmdEYXkoCiAgICAgICAgICBhY2FkZW1pY1Nlc3Npb246IGFjYWRlbWljU2Vzc2lvbiwKICAgICAgICAgIGZyb206IGRhdGUsCiAgICAgICAgKSwKICAgICAgKTsKICAgIH0KCiAgICByZXR1cm4gY29uc3QgQWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uKAogICAgICBhbGxvd2VkOiB0cnVlLAogICAgICBtZXNzYWdlOiAnSG9tZXdvcmsgZHVlIGRhdGUgaXMgdmFsaWQuJywKICAgICk7CiAgfQoKICBAb3ZlcnJpZGUKICBGdXR1cmU8QWNhZGVtaWNDYWxlbmRhclBvbGljeURlY2lzaW9uPiB2YWxpZGF0ZUV4YW1EYXRlKHsKICAgIHJlcXVpcmVkIFN0cmluZyBhY2FkZW1pY1Nlc3Npb24sCiAgICByZXF1aXJlZCBEYXRlVGltZSBkYXRlLAogIH0pIGFzeW5jIHsKICAgIGZpbmFsIGNvbmZpZyA9IGF3YWl0IF9yZXF1aXJlZENvbmZpZyhhY2FkZW1pY1Nlc3Npb24pOwoKICAgIGlmIChjb25maWcuaXNWYWNhdGlvbkRhdGUoZGF0ZSkgfHwKICAgICAgICBhd2FpdCBfaXNIb2xpZGF5KGFjYWRlbWljU2Vzc2lvbiwgZGF0ZSkpIHsKICAgICAgcmV0dXJuIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgICBhbGxvd2VkOiBmYWxzZSwKICAgICAgICBtZXNzYWdlOiAnRXhhbSBjYW5ub3QgYmUgc2NoZWR1bGVkIG9uIGEgaG9saWRheSBvciB2YWNhdGlvbi4nLAogICAgICApOwogICAgfQoKICAgIGZpbmFsIGluc2lkZVdpbmRvdyA9IGNvbmZpZy5leGFtV2luZG93cy5hbnkoCiAgICAgICh3aW5kb3cpID0+IF9pbnNpZGVSYW5nZShkYXRlLCB3aW5kb3cuc3RhcnREYXRlLCB3aW5kb3cuZW5kRGF0ZSksCiAgICApOwoKICAgIGlmIChjb25maWcuZXhhbVdpbmRvd3MuaXNOb3RFbXB0eSAmJiAhaW5zaWRlV2luZG93KSB7CiAgICAgIHJldHVybiBjb25zdCBBY2FkZW1pY0NhbGVuZGFyUG9saWN5RGVjaXNpb24oCiAgICAgICAgYWxsb3dlZDogZmFsc2UsCiAgICAgICAgbWVzc2FnZTogJ0V4YW0gZGF0ZSBpcyBvdXRzaWRlIGNvbmZpZ3VyZWQgZXhhbSB3aW5kb3dzLicsCiAgICAgICk7CiAgICB9CgogICAgcmV0dXJuIGNvbnN0IEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lEZWNpc2lvbigKICAgICAgYWxsb3dlZDogdHJ1ZSwKICAgICAgbWVzc2FnZTogJ0V4YW0gZGF0ZSBpcyB2YWxpZC4nLAogICAgKTsKICB9CgogIEBvdmVycmlkZQogIEZ1dHVyZTxEYXRlVGltZT4gcmVzb2x2ZUZlZUdlbmVyYXRpb25EYXRlKHsKICAgIHJlcXVpcmVkIFN0cmluZyBhY2FkZW1pY1Nlc3Npb24sCiAgICByZXF1aXJlZCBpbnQgbW9udGgsCiAgICByZXF1aXJlZCBpbnQgeWVhciwKICB9KSBhc3luYyB7CiAgICBmaW5hbCBjb25maWcgPSBhd2FpdCBfcmVxdWlyZWRDb25maWcoYWNhZGVtaWNTZXNzaW9uKTsKICAgIHJldHVybiBfcmVzb2x2ZVdvcmtpbmdEYXRlKAogICAgICBhY2FkZW1pY1Nlc3Npb24sCiAgICAgIERhdGVUaW1lKHllYXIsIG1vbnRoLCBjb25maWcuZmVlR2VuZXJhdGlvbkRheSksCiAgICApOwogIH0KCiAgQG92ZXJyaWRlCiAgRnV0dXJlPERhdGVUaW1lPiByZXNvbHZlRmVlRHVlRGF0ZSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgaW50IG1vbnRoLAogICAgcmVxdWlyZWQgaW50IHllYXIsCiAgfSkgYXN5bmMgewogICAgZmluYWwgY29uZmlnID0gYXdhaXQgX3JlcXVpcmVkQ29uZmlnKGFjYWRlbWljU2Vzc2lvbik7CiAgICByZXR1cm4gX3Jlc29sdmVXb3JraW5nRGF0ZSgKICAgICAgYWNhZGVtaWNTZXNzaW9uLAogICAgICBEYXRlVGltZSh5ZWFyLCBtb250aCwgY29uZmlnLmZlZUR1ZURheSksCiAgICApOwogIH0KCiAgQG92ZXJyaWRlCiAgRnV0dXJlPERhdGVUaW1lPiBuZXh0V29ya2luZ0RheSh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZnJvbSwKICB9KSBhc3luYyB7CiAgICB2YXIgY2FuZGlkYXRlID0gRGF0ZVRpbWUoZnJvbS55ZWFyLCBmcm9tLm1vbnRoLCBmcm9tLmRheSkKICAgICAgICAuYWRkKGNvbnN0IER1cmF0aW9uKGRheXM6IDEpKTsKCiAgICBmb3IgKHZhciBhdHRlbXB0ID0gMDsgYXR0ZW1wdCA8IDM3MDsgYXR0ZW1wdCsrKSB7CiAgICAgIGZpbmFsIGNvbmZpZyA9IGF3YWl0IF9yZXF1aXJlZENvbmZpZyhhY2FkZW1pY1Nlc3Npb24pOwogICAgICBmaW5hbCB3b3JraW5nID0gY29uZmlnLndvcmtpbmdXZWVrZGF5cy5jb250YWlucyhjYW5kaWRhdGUud2Vla2RheSkgJiYKICAgICAgICAgICFjb25maWcuaXNWYWNhdGlvbkRhdGUoY2FuZGlkYXRlKSAmJgogICAgICAgICAgIWF3YWl0IF9pc0hvbGlkYXkoYWNhZGVtaWNTZXNzaW9uLCBjYW5kaWRhdGUpOwoKICAgICAgaWYgKHdvcmtpbmcpIHJldHVybiBjYW5kaWRhdGU7CiAgICAgIGNhbmRpZGF0ZSA9IGNhbmRpZGF0ZS5hZGQoY29uc3QgRHVyYXRpb24oZGF5czogMSkpOwogICAgfQoKICAgIHRocm93IFN0YXRlRXJyb3IoJ05vIHdvcmtpbmcgZGF5IGNvdWxkIGJlIHJlc29sdmVkLicpOwogIH0KCiAgQG92ZXJyaWRlCiAgRnV0dXJlPExpc3Q8QWNhZGVtaWNDYWxlbmRhckV2ZW50RW50aXR5Pj4gZ2V0VmlzaWJsZUV2ZW50cyh7CiAgICByZXF1aXJlZCBTdHJpbmcgYWNhZGVtaWNTZXNzaW9uLAogICAgcmVxdWlyZWQgQWNhZGVtaWNDYWxlbmRhckF1ZGllbmNlIGF1ZGllbmNlLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgc3RhcnREYXRlLAogICAgcmVxdWlyZWQgRGF0ZVRpbWUgZW5kRGF0ZSwKICAgIExpc3Q8U3RyaW5nPiBjbGFzc0lkcyA9IGNvbnN0IFtdLAogIH0pIGFzeW5jIHsKICAgIGZpbmFsIGV2ZW50cyA9IGF3YWl0IF9jYWxlbmRhclJlcG9zaXRvcnkuZ2V0RXZlbnRzKAogICAgICBhY2FkZW1pY1Nlc3Npb246IGFjYWRlbWljU2Vzc2lvbiwKICAgICAgc3RhcnREYXRlOiBzdGFydERhdGUsCiAgICAgIGVuZERhdGU6IGVuZERhdGUsCiAgICAgIGlzQWN0aXZlOiB0cnVlLAogICAgKTsKCiAgICByZXR1cm4gZXZlbnRzLndoZXJlKChldmVudCkgewogICAgICBpZiAoZXZlbnQuYXVkaWVuY2UgPT0gQWNhZGVtaWNDYWxlbmRhckF1ZGllbmNlLndob2xlU2Nob29sKSB7CiAgICAgICAgcmV0dXJuIHRydWU7CiAgICAgIH0KICAgICAgaWYgKGV2ZW50LmF1ZGllbmNlID09IGF1ZGllbmNlKSByZXR1cm4gdHJ1ZTsKICAgICAgaWYgKGV2ZW50LmF1ZGllbmNlID09IEFjYWRlbWljQ2FsZW5kYXJBdWRpZW5jZS5zZWxlY3RlZENsYXNzZXMpIHsKICAgICAgICByZXR1cm4gZXZlbnQuY2xhc3NJZHMuYW55KGNsYXNzSWRzLmNvbnRhaW5zKTsKICAgICAgfQogICAgICByZXR1cm4gZmFsc2U7CiAgICB9KS50b0xpc3QoZ3Jvd2FibGU6IGZhbHNlKTsKICB9CgogIEZ1dHVyZTxBY2FkZW1pY1llYXJDb25maWdFbnRpdHk+IF9yZXF1aXJlZENvbmZpZygKICAgIFN0cmluZyBzZXNzaW9uLAogICkgYXN5bmMgewogICAgZmluYWwgY29uZmlnID0gYXdhaXQgX2NvbmZpZ1JlcG9zaXRvcnkuZ2V0QnlTZXNzaW9uKHNlc3Npb24pOwogICAgaWYgKGNvbmZpZyA9PSBudWxsKSB7CiAgICAgIHRocm93IFN0YXRlRXJyb3IoCiAgICAgICAgJ0FjYWRlbWljIFllYXIgV2l6YXJkIGNvbmZpZ3VyYXRpb24gaXMgbWlzc2luZyBmb3IgJHNlc3Npb24uJywKICAgICAgKTsKICAgIH0KICAgIHJldHVybiBjb25maWc7CiAgfQoKICBGdXR1cmU8Ym9vbD4gX2lzSG9saWRheShTdHJpbmcgc2Vzc2lvbiwgRGF0ZVRpbWUgZGF0ZSkgYXN5bmMgewogICAgZmluYWwgZXZlbnRzID0gYXdhaXQgX2NhbGVuZGFyUmVwb3NpdG9yeS5nZXRFdmVudHMoCiAgICAgIGFjYWRlbWljU2Vzc2lvbjogc2Vzc2lvbiwKICAgICAgc3RhcnREYXRlOiBkYXRlLAogICAgICBlbmREYXRlOiBkYXRlLAogICAgICBpc0FjdGl2ZTogdHJ1ZSwKICAgICk7CgogICAgcmV0dXJuIGV2ZW50cy5hbnkoCiAgICAgIChldmVudCkgPT4KICAgICAgICAgIGV2ZW50LnR5cGUgPT0gQWNhZGVtaWNDYWxlbmRhckV2ZW50VHlwZS5ob2xpZGF5IHx8CiAgICAgICAgICBldmVudC50eXBlID09IEFjYWRlbWljQ2FsZW5kYXJFdmVudFR5cGUudmFjYXRpb24sCiAgICApOwogIH0KCiAgRnV0dXJlPERhdGVUaW1lPiBfcmVzb2x2ZVdvcmtpbmdEYXRlKAogICAgU3RyaW5nIHNlc3Npb24sCiAgICBEYXRlVGltZSBkYXRlLAogICkgYXN5bmMgewogICAgZmluYWwgY29uZmlnID0gYXdhaXQgX3JlcXVpcmVkQ29uZmlnKHNlc3Npb24pOwogICAgZmluYWwgaXNXb3JraW5nID0gY29uZmlnLndvcmtpbmdXZWVrZGF5cy5jb250YWlucyhkYXRlLndlZWtkYXkpICYmCiAgICAgICAgIWNvbmZpZy5pc1ZhY2F0aW9uRGF0ZShkYXRlKSAmJgogICAgICAgICFhd2FpdCBfaXNIb2xpZGF5KHNlc3Npb24sIGRhdGUpOwoKICAgIGlmIChpc1dvcmtpbmcpIHJldHVybiBkYXRlOwoKICAgIHJldHVybiBuZXh0V29ya2luZ0RheSgKICAgICAgYWNhZGVtaWNTZXNzaW9uOiBzZXNzaW9uLAogICAgICBmcm9tOiBkYXRlLnN1YnRyYWN0KGNvbnN0IER1cmF0aW9uKGRheXM6IDEpKSwKICAgICk7CiAgfQoKICBzdGF0aWMgYm9vbCBfaW5zaWRlU2Vzc2lvbigKICAgIEFjYWRlbWljWWVhckNvbmZpZ0VudGl0eSBjb25maWcsCiAgICBEYXRlVGltZSBkYXRlLAogICkgPT4KICAgICAgX2luc2lkZVJhbmdlKGRhdGUsIGNvbmZpZy5zdGFydERhdGUsIGNvbmZpZy5lbmREYXRlKTsKCiAgc3RhdGljIGJvb2wgX2luc2lkZVJhbmdlKAogICAgRGF0ZVRpbWUgZGF0ZSwKICAgIERhdGVUaW1lIHN0YXJ0LAogICAgRGF0ZVRpbWUgZW5kLAogICkgewogICAgZmluYWwgZGF5ID0gRGF0ZVRpbWUoZGF0ZS55ZWFyLCBkYXRlLm1vbnRoLCBkYXRlLmRheSk7CiAgICBmaW5hbCBmcm9tID0gRGF0ZVRpbWUoc3RhcnQueWVhciwgc3RhcnQubW9udGgsIHN0YXJ0LmRheSk7CiAgICBmaW5hbCB0byA9IERhdGVUaW1lKGVuZC55ZWFyLCBlbmQubW9udGgsIGVuZC5kYXkpOwogICAgcmV0dXJuICFkYXkuaXNCZWZvcmUoZnJvbSkgJiYgIWRheS5pc0FmdGVyKHRvKTsKICB9Cn0K'
    'lib/features/academic_calendar/presentation/pages/academic_calendar_integration_page.dart' = 'aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CgppbXBvcnQgJy4uLy4uLy4uLy4uL2NvcmUvZGkvc2VydmljZV9sb2NhdG9yLmRhcnQnOwppbXBvcnQgJy4uLy4uL2RvbWFpbi9lbnRpdGllcy9hY2FkZW1pY195ZWFyX2NvbmZpZ19lbnRpdHkuZGFydCc7CmltcG9ydCAnLi4vLi4vZG9tYWluL3NlcnZpY2VzL2FjYWRlbWljX2NhbGVuZGFyX3BvbGljeV9zZXJ2aWNlLmRhcnQnOwoKY2xhc3MgQWNhZGVtaWNDYWxlbmRhckludGVncmF0aW9uUGFnZSBleHRlbmRzIFN0YXRlZnVsV2lkZ2V0IHsKICBjb25zdCBBY2FkZW1pY0NhbGVuZGFySW50ZWdyYXRpb25QYWdlKHsKICAgIHN1cGVyLmtleSwKICAgIHRoaXMuYWNhZGVtaWNTZXNzaW9uID0gJzIwMjYtMjAyNycsCiAgfSk7CgogIGZpbmFsIFN0cmluZyBhY2FkZW1pY1Nlc3Npb247CgogIEBvdmVycmlkZQogIFN0YXRlPEFjYWRlbWljQ2FsZW5kYXJJbnRlZ3JhdGlvblBhZ2U+IGNyZWF0ZVN0YXRlKCkgPT4KICAgICAgX0FjYWRlbWljQ2FsZW5kYXJJbnRlZ3JhdGlvblBhZ2VTdGF0ZSgpOwp9CgpjbGFzcyBfQWNhZGVtaWNDYWxlbmRhckludGVncmF0aW9uUGFnZVN0YXRlCiAgICBleHRlbmRzIFN0YXRlPEFjYWRlbWljQ2FsZW5kYXJJbnRlZ3JhdGlvblBhZ2U+IHsKICBsYXRlIGZpbmFsIFRleHRFZGl0aW5nQ29udHJvbGxlciBfc2Vzc2lvbkNvbnRyb2xsZXI7CiAgQWNhZGVtaWNZZWFyQ29uZmlnRW50aXR5PyBfY29uZmlnOwogIERhdGVUaW1lPyBfZmVlR2VuZXJhdGlvbkRhdGU7CiAgRGF0ZVRpbWU/IF9mZWVEdWVEYXRlOwogIGJvb2wgX2xvYWRpbmcgPSB0cnVlOwogIFN0cmluZz8gX2Vycm9yOwoKICBAb3ZlcnJpZGUKICB2b2lkIGluaXRTdGF0ZSgpIHsKICAgIHN1cGVyLmluaXRTdGF0ZSgpOwogICAgX3Nlc3Npb25Db250cm9sbGVyID0KICAgICAgICBUZXh0RWRpdGluZ0NvbnRyb2xsZXIodGV4dDogd2lkZ2V0LmFjYWRlbWljU2Vzc2lvbik7CiAgICBfbG9hZCgpOwogIH0KCiAgQG92ZXJyaWRlCiAgdm9pZCBkaXNwb3NlKCkgewogICAgX3Nlc3Npb25Db250cm9sbGVyLmRpc3Bvc2UoKTsKICAgIHN1cGVyLmRpc3Bvc2UoKTsKICB9CgogIEZ1dHVyZTx2b2lkPiBfbG9hZCgpIGFzeW5jIHsKICAgIHNldFN0YXRlKCgpIHsKICAgICAgX2xvYWRpbmcgPSB0cnVlOwogICAgICBfZXJyb3IgPSBudWxsOwogICAgfSk7CgogICAgdHJ5IHsKICAgICAgZmluYWwgc2VydmljZSA9IHNsPEFjYWRlbWljQ2FsZW5kYXJQb2xpY3lTZXJ2aWNlPigpOwogICAgICBmaW5hbCBub3cgPSBEYXRlVGltZS5ub3coKTsKICAgICAgZmluYWwgY29uZmlnID0KICAgICAgICAgIGF3YWl0IHNlcnZpY2UuZ2V0Q29uZmlnKF9zZXNzaW9uQ29udHJvbGxlci50ZXh0LnRyaW0oKSk7CgogICAgICBpZiAoY29uZmlnID09IG51bGwpIHsKICAgICAgICB0aHJvdyBTdGF0ZUVycm9yKCdBY2FkZW1pYyBZZWFyIFdpemFyZCBjb25maWd1cmF0aW9uIGlzIG1pc3NpbmcuJyk7CiAgICAgIH0KCiAgICAgIGZpbmFsIGdlbmVyYXRpb24gPSBhd2FpdCBzZXJ2aWNlLnJlc29sdmVGZWVHZW5lcmF0aW9uRGF0ZSgKICAgICAgICBhY2FkZW1pY1Nlc3Npb246IGNvbmZpZy5hY2FkZW1pY1Nlc3Npb24sCiAgICAgICAgbW9udGg6IG5vdy5tb250aCwKICAgICAgICB5ZWFyOiBub3cueWVhciwKICAgICAgKTsKICAgICAgZmluYWwgZHVlID0gYXdhaXQgc2VydmljZS5yZXNvbHZlRmVlRHVlRGF0ZSgKICAgICAgICBhY2FkZW1pY1Nlc3Npb246IGNvbmZpZy5hY2FkZW1pY1Nlc3Npb24sCiAgICAgICAgbW9udGg6IG5vdy5tb250aCwKICAgICAgICB5ZWFyOiBub3cueWVhciwKICAgICAgKTsKCiAgICAgIGlmICghbW91bnRlZCkgcmV0dXJuOwogICAgICBzZXRTdGF0ZSgoKSB7CiAgICAgICAgX2NvbmZpZyA9IGNvbmZpZzsKICAgICAgICBfZmVlR2VuZXJhdGlvbkRhdGUgPSBnZW5lcmF0aW9uOwogICAgICAgIF9mZWVEdWVEYXRlID0gZHVlOwogICAgICAgIF9sb2FkaW5nID0gZmFsc2U7CiAgICAgIH0pOwogICAgfSBjYXRjaCAoZXJyb3IpIHsKICAgICAgaWYgKCFtb3VudGVkKSByZXR1cm47CiAgICAgIHNldFN0YXRlKCgpIHsKICAgICAgICBfbG9hZGluZyA9IGZhbHNlOwogICAgICAgIF9lcnJvciA9IGVycm9yLnRvU3RyaW5nKCkucmVwbGFjZUZpcnN0KCdTdGF0ZUVycm9yOiAnLCAnJyk7CiAgICAgIH0pOwogICAgfQogIH0KCiAgQG92ZXJyaWRlCiAgV2lkZ2V0IGJ1aWxkKEJ1aWxkQ29udGV4dCBjb250ZXh0KSB7CiAgICByZXR1cm4gU2NhZmZvbGQoCiAgICAgIGFwcEJhcjogQXBwQmFyKHRpdGxlOiBjb25zdCBUZXh0KCdFUlAgQ2FsZW5kYXIgSW50ZWdyYXRpb24nKSksCiAgICAgIGJvZHk6IF9sb2FkaW5nCiAgICAgICAgICA/IGNvbnN0IENlbnRlcihjaGlsZDogQ2lyY3VsYXJQcm9ncmVzc0luZGljYXRvcigpKQogICAgICAgICAgOiBfZXJyb3IgIT0gbnVsbAogICAgICAgICAgICAgID8gQ2VudGVyKGNoaWxkOiBUZXh0KF9lcnJvciEpKQogICAgICAgICAgICAgIDogTGlzdFZpZXcoCiAgICAgICAgICAgICAgICAgIHBhZGRpbmc6IGNvbnN0IEVkZ2VJbnNldHMuYWxsKDIwKSwKICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgICAgICAgICAgICBDYXJkKAogICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFBhZGRpbmcoCiAgICAgICAgICAgICAgICAgICAgICAgIHBhZGRpbmc6IGNvbnN0IEVkZ2VJbnNldHMuYWxsKDE2KSwKICAgICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFdyYXAoCiAgICAgICAgICAgICAgICAgICAgICAgICAgc3BhY2luZzogMTIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgcnVuU3BhY2luZzogMTIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgY3Jvc3NBeGlzQWxpZ25tZW50OiBXcmFwQ3Jvc3NBbGlnbm1lbnQuY2VudGVyLAogICAgICAgICAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBTaXplZEJveCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgd2lkdGg6IDE5MCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY2hpbGQ6IFRleHRGb3JtRmllbGQoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgY29udHJvbGxlcjogX3Nlc3Npb25Db250cm9sbGVyLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRlY29yYXRpb246IGNvbnN0IElucHV0RGVjb3JhdGlvbigKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVsVGV4dDogJ0FjYWRlbWljIFNlc3Npb24nLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYm9yZGVyOiBPdXRsaW5lSW5wdXRCb3JkZXIoKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIEZpbGxlZEJ1dHRvbi5pY29uKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBvblByZXNzZWQ6IF9sb2FkLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBpY29uOiBjb25zdCBJY29uKEljb25zLnJlZnJlc2gpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogY29uc3QgVGV4dCgnUmVsb2FkJyksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgY29uc3QgU2l6ZWRCb3goaGVpZ2h0OiAxNCksCiAgICAgICAgICAgICAgICAgICAgX2ludGVncmF0aW9uQ2FyZCgKICAgICAgICAgICAgICAgICAgICAgIGljb246IEljb25zLmZhY3RfY2hlY2tfb3V0bGluZWQsCiAgICAgICAgICAgICAgICAgICAgICB0aXRsZTogJ0F0dGVuZGFuY2UnLAogICAgICAgICAgICAgICAgICAgICAgc3RhdHVzOiAnQ29ubmVjdGVkJywKICAgICAgICAgICAgICAgICAgICAgIGRlc2NyaXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICdXb3JraW5nLWRheSwgaG9saWRheSBhbmQgdmFjYXRpb24gdmFsaWRhdGlvbiBpcyBhdmFpbGFibGUuJywKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgIF9pbnRlZ3JhdGlvbkNhcmQoCiAgICAgICAgICAgICAgICAgICAgICBpY29uOiBJY29ucy5zY2hlZHVsZV9vdXRsaW5lZCwKICAgICAgICAgICAgICAgICAgICAgIHRpdGxlOiAnVGltZXRhYmxlJywKICAgICAgICAgICAgICAgICAgICAgIHN0YXR1czogJ0Nvbm5lY3RlZCcsCiAgICAgICAgICAgICAgICAgICAgICBkZXNjcmlwdGlvbjoKICAgICAgICAgICAgICAgICAgICAgICAgICAnU2F0dXJkYXkgYW5kIHplcm8tcGVyaW9kIHJ1bGVzIGFyZSBhdmFpbGFibGUgdG8gdGltZXRhYmxlIGdlbmVyYXRpb24uJywKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgIF9pbnRlZ3JhdGlvbkNhcmQoCiAgICAgICAgICAgICAgICAgICAgICBpY29uOiBJY29ucy5tZW51X2Jvb2tfb3V0bGluZWQsCiAgICAgICAgICAgICAgICAgICAgICB0aXRsZTogJ0hvbWV3b3JrJywKICAgICAgICAgICAgICAgICAgICAgIHN0YXR1czogJ0Nvbm5lY3RlZCcsCiAgICAgICAgICAgICAgICAgICAgICBkZXNjcmlwdGlvbjoKICAgICAgICAgICAgICAgICAgICAgICAgICAnSG9saWRheSwgdmFjYXRpb24gYW5kIGFsbG93ZWQtd2Vla2RheSB2YWxpZGF0aW9uIGlzIGF2YWlsYWJsZS4nLAogICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgX2ludGVncmF0aW9uQ2FyZCgKICAgICAgICAgICAgICAgICAgICAgIGljb246IEljb25zLnF1aXpfb3V0bGluZWQsCiAgICAgICAgICAgICAgICAgICAgICB0aXRsZTogJ0V4YW1zICYgRGF0ZSBTaGVldHMnLAogICAgICAgICAgICAgICAgICAgICAgc3RhdHVzOiAnQ29ubmVjdGVkJywKICAgICAgICAgICAgICAgICAgICAgIGRlc2NyaXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICdFeGFtLXdpbmRvdywgaG9saWRheSBhbmQgdmFjYXRpb24gY2hlY2tzIGFyZSBhdmFpbGFibGUuJywKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgIF9pbnRlZ3JhdGlvbkNhcmQoCiAgICAgICAgICAgICAgICAgICAgICBpY29uOiBJY29ucy5wYXltZW50c19vdXRsaW5lZCwKICAgICAgICAgICAgICAgICAgICAgIHRpdGxlOiAnRmVlIE1hbmFnZW1lbnQnLAogICAgICAgICAgICAgICAgICAgICAgc3RhdHVzOiAnQ29ubmVjdGVkJywKICAgICAgICAgICAgICAgICAgICAgIGRlc2NyaXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICdDdXJyZW50IHJlc29sdmVkIGRhdGVzOiBnZW5lcmF0aW9uICR7X2RhdGUoX2ZlZUdlbmVyYXRpb25EYXRlISl9OyBkdWUgJHtfZGF0ZShfZmVlRHVlRGF0ZSEpfS4nLAogICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgX2ludGVncmF0aW9uQ2FyZCgKICAgICAgICAgICAgICAgICAgICAgIGljb246IEljb25zLnBlb3BsZV9vdXRsaW5lLAogICAgICAgICAgICAgICAgICAgICAgdGl0bGU6ICdQYXJlbnQgJiBUZWFjaGVyIFBvcnRhbHMnLAogICAgICAgICAgICAgICAgICAgICAgc3RhdHVzOiAnQ29ubmVjdGVkJywKICAgICAgICAgICAgICAgICAgICAgIGRlc2NyaXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICdBdWRpZW5jZS1maWx0ZXJlZCBjYWxlbmRhciBldmVudHMgYXJlIGF2YWlsYWJsZSB0aHJvdWdoIHRoZSBwb2xpY3kgc2VydmljZS4nLAogICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgY29uc3QgU2l6ZWRCb3goaGVpZ2h0OiAxNCksCiAgICAgICAgICAgICAgICAgICAgQ2FyZCgKICAgICAgICAgICAgICAgICAgICAgIGNoaWxkOiBQYWRkaW5nKAogICAgICAgICAgICAgICAgICAgICAgICBwYWRkaW5nOiBjb25zdCBFZGdlSW5zZXRzLmFsbCgxNiksCiAgICAgICAgICAgICAgICAgICAgICAgIGNoaWxkOiBXcmFwKAogICAgICAgICAgICAgICAgICAgICAgICAgIHNwYWNpbmc6IDEwLAogICAgICAgICAgICAgICAgICAgICAgICAgIHJ1blNwYWNpbmc6IDEwLAogICAgICAgICAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBDaGlwKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogVGV4dCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnV29ya2luZyBEYXlzOiAke19jb25maWchLnRvdGFsV29ya2luZ0RheXN9JywKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBDaGlwKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogVGV4dCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnVGVhY2hpbmcgRGF5czogJHtfY29uZmlnIS5hdmFpbGFibGVUZWFjaGluZ0RheXN9JywKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBDaGlwKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogVGV4dCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAnRXhhbSBXaW5kb3dzOiAke19jb25maWchLmV4YW1XaW5kb3dzLmxlbmd0aH0nLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIENoaXAoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiBUZXh0KAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICdWYWNhdGlvbnM6ICR7X2NvbmZpZyEudmFjYXRpb25zLmxlbmd0aH0nLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgKSwKICAgICk7CiAgfQoKICBXaWRnZXQgX2ludGVncmF0aW9uQ2FyZCh7CiAgICByZXF1aXJlZCBJY29uRGF0YSBpY29uLAogICAgcmVxdWlyZWQgU3RyaW5nIHRpdGxlLAogICAgcmVxdWlyZWQgU3RyaW5nIHN0YXR1cywKICAgIHJlcXVpcmVkIFN0cmluZyBkZXNjcmlwdGlvbiwKICB9KSB7CiAgICByZXR1cm4gQ2FyZCgKICAgICAgY2hpbGQ6IExpc3RUaWxlKAogICAgICAgIGxlYWRpbmc6IENpcmNsZUF2YXRhcihjaGlsZDogSWNvbihpY29uKSksCiAgICAgICAgdGl0bGU6IFRleHQodGl0bGUpLAogICAgICAgIHN1YnRpdGxlOiBUZXh0KGRlc2NyaXB0aW9uKSwKICAgICAgICB0cmFpbGluZzogQ2hpcChsYWJlbDogVGV4dChzdGF0dXMpKSwKICAgICAgKSwKICAgICk7CiAgfQoKICBzdGF0aWMgU3RyaW5nIF9kYXRlKERhdGVUaW1lIHZhbHVlKSA9PgogICAgICAnJHt2YWx1ZS5kYXkudG9TdHJpbmcoKS5wYWRMZWZ0KDIsICcwJyl9LycKICAgICAgJyR7dmFsdWUubW9udGgudG9TdHJpbmcoKS5wYWRMZWZ0KDIsICcwJyl9LycKICAgICAgJyR7dmFsdWUueWVhcn0nOwp9Cg=='
}
$serviceLocator = 'lib/core/di/service_locator.dart'
$calendarPage = 'lib/features/academic_calendar/presentation/pages/academic_calendar_page.dart'
$feePage = 'lib/features/fees/presentation/pages/monthly_fee_generation_page.dart'

foreach ($relativePath in (@($serviceLocator, $calendarPage, $feePage) + $payloads.Keys)) {
    Backup-ProjectFile -RelativePath $relativePath
}

foreach ($item in $payloads.GetEnumerator()) {
    $text = [Text.Encoding]::UTF8.GetString(
        [Convert]::FromBase64String($item.Value)
    )
    Write-ProjectFile -RelativePath $item.Key -Content $text
}

# Service locator
$content = Read-ProjectFile -RelativePath $serviceLocator

$content = Ensure-BeforeAnchor `
    -Content $content `
    -UniqueMarker 'academic_calendar_policy_service_impl.dart' `
    -Anchor "import '../../features/academic_calendar/data/repositories/academic_year_config_repository_impl.dart';" `
    -Block "import '../../features/academic_calendar/data/services/academic_calendar_policy_service_impl.dart';`n"

$content = Ensure-BeforeAnchor `
    -Content $content `
    -UniqueMarker 'academic_calendar_policy_service.dart' `
    -Anchor "import '../../features/academic_calendar/domain/repositories/academic_year_config_repository.dart';" `
    -Block "import '../../features/academic_calendar/domain/services/academic_calendar_policy_service.dart';`n"

$serviceRegistration = @'
  sl.registerLazySingleton<AcademicCalendarPolicyService>(
    () => AcademicCalendarPolicyServiceImpl(
      sl<AcademicYearConfigRepository>(),
      sl<AcademicCalendarRepository>(),
    ),
  );

'@

$content = Ensure-BeforeAnchor `
    -Content $content `
    -UniqueMarker 'registerLazySingleton<AcademicCalendarPolicyService>' `
    -Anchor '  sl.registerLazySingleton<AcademicYearConfigRepository>(' `
    -Block $serviceRegistration

Write-ProjectFile -RelativePath $serviceLocator -Content $content

# Calendar page integration button
$content = Read-ProjectFile -RelativePath $calendarPage

if (-not $content.Contains(
    "import 'academic_calendar_integration_page.dart';"
)) {
    $content = $content.Replace(
        "import 'academic_calendar_validation_page.dart';",
        "import 'academic_calendar_integration_page.dart';`nimport 'academic_calendar_validation_page.dart';"
    )
}

if (-not $content.Contains(
    'const AcademicCalendarIntegrationPage('
)) {
    $validationMarker = @'
          TextButton.icon(
            onPressed: () {
              Navigator.of(context).push<void>(
                MaterialPageRoute<void>(
                  builder: (_) => AcademicCalendarValidationPage(
                    academicSession: _sessionController.text.trim(),
                  ),
                ),
              );
            },
            icon: const Icon(Icons.fact_check_outlined),
            label: const Text('Validate'),
          ),
'@

    if (-not $content.Contains($validationMarker)) {
        throw 'Could not locate the Validate AppBar action.'
    }

    $integrationAction = @'
          TextButton.icon(
            onPressed: () {
              Navigator.of(context).push<void>(
                MaterialPageRoute<void>(
                  builder: (_) => AcademicCalendarIntegrationPage(
                    academicSession: _sessionController.text.trim(),
                  ),
                ),
              );
            },
            icon: const Icon(Icons.hub_outlined),
            label: const Text('Integrations'),
          ),
'@

    $content = $content.Replace(
        $validationMarker,
        $integrationAction + $validationMarker
    )
}

Write-ProjectFile -RelativePath $calendarPage -Content $content

# Fee Management integration: load configured due day.
$content = Read-ProjectFile -RelativePath $feePage

if (-not $content.Contains(
    "academic_calendar/domain/services/academic_calendar_policy_service.dart"
)) {
    $content = $content.Replace(
        "import '../../../../core/di/service_locator.dart';",
        "import '../../../../core/di/service_locator.dart';`nimport '../../../academic_calendar/domain/services/academic_calendar_policy_service.dart';"
    )
}

if (-not $content.Contains('_loadCalendarFeeDefaults')) {
    $initMarker = @'
  @override
  void initState() {
    super.initState();
    _loadAssignments();
  }
'@
    $replacement = @'
  @override
  void initState() {
    super.initState();
    _loadCalendarFeeDefaults();
    _loadAssignments();
  }

  Future<void> _loadCalendarFeeDefaults() async {
    try {
      final service = sl<AcademicCalendarPolicyService>();
      final config = await service.getConfig(
        _sessionController.text.trim(),
      );
      if (!mounted || config == null) return;
      setState(() {
        _dueDayController.text = '${config.feeDueDay}';
      });
    } catch (_) {
      // Keep the existing default when Academic Year Wizard is not ready.
    }
  }
'@

    if (-not $content.Contains($initMarker)) {
        throw 'Monthly Fee Generation initState anchor not found.'
    }
    $content = $content.Replace($initMarker, $replacement)
}

Write-ProjectFile -RelativePath $feePage -Content $content

$formatFiles = @($serviceLocator, $calendarPage, $feePage) + $payloads.Keys

Write-Host ''
Write-Host 'Running dart format...' -ForegroundColor Cyan
& dart format $formatFiles
if ($LASTEXITCODE -ne 0) {
    throw 'dart format failed.'
}

Write-Host ''
Write-Host 'Running flutter analyze...' -ForegroundColor Cyan
& flutter analyze
if ($LASTEXITCODE -ne 0) {
    throw 'flutter analyze found issues. Copy the complete output into ChatGPT.'
}

Write-Host ''
Write-Host 'Academic Calendar Phase 4 ERP Integration completed successfully.' -ForegroundColor Green
Write-Host 'Academic Calendar is ready to freeze after final QA.' -ForegroundColor Cyan
Write-Host "Backup: $backupRoot" -ForegroundColor DarkGray
