$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$root = (Get-Location).Path
if (-not (Test-Path (Join-Path $root 'pubspec.yaml'))) {
    throw 'Run this script from the almustafa-connect-erp project root.'
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupRoot = Join-Path (Split-Path $root -Parent) "almustafa-connect-erp_backups/access_control_phase4_$stamp"

function Read-ProjectFile {
    param([Parameter(Mandatory = $true)][string]$RelativePath)

    $path = Join-Path $root $RelativePath
    if (-not (Test-Path $path)) {
        throw "Required file not found: $RelativePath"
    }

    return [IO.File]::ReadAllText($path).Replace("`r`n", "`n")
}

function Write-ProjectFile {
    param(
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $path = Join-Path $root $RelativePath
    New-Item -ItemType Directory -Path (Split-Path $path -Parent) -Force | Out-Null
    [IO.File]::WriteAllText($path, $Content, $utf8)
    Write-Host "Created/updated: $RelativePath" -ForegroundColor Green
}

function Backup-ProjectFile {
    param([Parameter(Mandatory = $true)][string]$RelativePath)

    $source = Join-Path $root $RelativePath
    if (-not (Test-Path $source)) { return }

    $destination = Join-Path $backupRoot $RelativePath
    New-Item -ItemType Directory -Path (Split-Path $destination -Parent) -Force | Out-Null
    Copy-Item $source $destination -Force
}

function Add-Import {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [Parameter(Mandatory = $true)][string]$ImportLine
    )

    if ($Content.Contains($ImportLine)) { return $Content }

    $matches = [regex]::Matches(
        $Content,
        "(?m)^import\s+['""].+?['""];\s*$"
    )

    if ($matches.Count -eq 0) {
        throw "Import block not found: $ImportLine"
    }

    $last = $matches[$matches.Count - 1]

    return $Content.Insert(
        $last.Index + $last.Length,
        "`n$ImportLine"
    )
}

$payloads = @{
    'firestore.rules' = 'cnVsZXNfdmVyc2lvbiA9ICcyJzsKCnNlcnZpY2UgY2xvdWQuZmlyZXN0b3JlIHsKICBtYXRjaCAvZGF0YWJhc2VzL3tkYXRhYmFzZX0vZG9jdW1lbnRzIHsKICAgIGZ1bmN0aW9uIHNpZ25lZEluKCkgewogICAgICByZXR1cm4gcmVxdWVzdC5hdXRoICE9IG51bGw7CiAgICB9CgogICAgZnVuY3Rpb24gYXNzaWdubWVudFBhdGgoKSB7CiAgICAgIHJldHVybiAvZGF0YWJhc2VzLyQoZGF0YWJhc2UpL2RvY3VtZW50cy91c2VyX3JvbGVzLyQocmVxdWVzdC5hdXRoLnVpZCk7CiAgICB9CgogICAgZnVuY3Rpb24gaGFzQXNzaWdubWVudCgpIHsKICAgICAgcmV0dXJuIHNpZ25lZEluKCkgJiYgZXhpc3RzKGFzc2lnbm1lbnRQYXRoKCkpOwogICAgfQoKICAgIGZ1bmN0aW9uIGFzc2lnbm1lbnQoKSB7CiAgICAgIHJldHVybiBnZXQoYXNzaWdubWVudFBhdGgoKSkuZGF0YTsKICAgIH0KCiAgICBmdW5jdGlvbiBhY3RpdmVBc3NpZ25tZW50KCkgewogICAgICByZXR1cm4gaGFzQXNzaWdubWVudCgpICYmIGFzc2lnbm1lbnQoKS5pc0FjdGl2ZSA9PSB0cnVlOwogICAgfQoKICAgIGZ1bmN0aW9uIHJvbGVQYXRoKCkgewogICAgICByZXR1cm4gL2RhdGFiYXNlcy8kKGRhdGFiYXNlKS9kb2N1bWVudHMvYXBwX3JvbGVzLyQoYXNzaWdubWVudCgpLnJvbGVJZCk7CiAgICB9CgogICAgZnVuY3Rpb24gaGFzQWN0aXZlUm9sZSgpIHsKICAgICAgcmV0dXJuIGFjdGl2ZUFzc2lnbm1lbnQoKQogICAgICAgICAgJiYgZXhpc3RzKHJvbGVQYXRoKCkpCiAgICAgICAgICAmJiBnZXQocm9sZVBhdGgoKSkuZGF0YS5pc0FjdGl2ZSA9PSB0cnVlOwogICAgfQoKICAgIGZ1bmN0aW9uIHBlcm1pc3Npb25zKCkgewogICAgICByZXR1cm4gaGFzQWN0aXZlUm9sZSgpCiAgICAgICAgICA/IGdldChyb2xlUGF0aCgpKS5kYXRhLnBlcm1pc3Npb25zCiAgICAgICAgICA6IFtdOwogICAgfQoKICAgIGZ1bmN0aW9uIGhhc1Blcm1pc3Npb24ocGVybWlzc2lvbikgewogICAgICByZXR1cm4gaGFzQWN0aXZlUm9sZSgpICYmIHBlcm1pc3Npb24gaW4gcGVybWlzc2lvbnMoKTsKICAgIH0KCiAgICBmdW5jdGlvbiBoYXNBbnlQZXJtaXNzaW9uKGEsIGIpIHsKICAgICAgcmV0dXJuIGhhc1Blcm1pc3Npb24oYSkgfHwgaGFzUGVybWlzc2lvbihiKTsKICAgIH0KCiAgICBmdW5jdGlvbiBpc1N1cGVyQWRtaW4oKSB7CiAgICAgIHJldHVybiBoYXNBY3RpdmVSb2xlKCkKICAgICAgICAgICYmICgKICAgICAgICAgICAgYXNzaWdubWVudCgpLnJvbGVJZCA9PSAnc3VwZXJfYWRtaW4nCiAgICAgICAgICAgIHx8IGhhc1Blcm1pc3Npb24oJ3JvbGVzTWFuYWdlJykKICAgICAgICAgICk7CiAgICB9CgogICAgZnVuY3Rpb24gb3duc1BhcmVudEFjY291bnQocGFyZW50SWQpIHsKICAgICAgcmV0dXJuIHNpZ25lZEluKCkKICAgICAgICAgICYmIGV4aXN0cygKICAgICAgICAgICAgL2RhdGFiYXNlcy8kKGRhdGFiYXNlKS9kb2N1bWVudHMvcGFyZW50X2FjY291bnRzLyQocGFyZW50SWQpCiAgICAgICAgICApCiAgICAgICAgICAmJiByZXF1ZXN0LmF1dGgudWlkID09CiAgICAgICAgICAgICAgZ2V0KAogICAgICAgICAgICAgICAgL2RhdGFiYXNlcy8kKGRhdGFiYXNlKS9kb2N1bWVudHMvcGFyZW50X2FjY291bnRzLyQocGFyZW50SWQpCiAgICAgICAgICAgICAgKS5kYXRhLmF1dGhVc2VySWQ7CiAgICB9CgogICAgZnVuY3Rpb24gaXNMaW5rZWRQYXJlbnRTdHVkZW50KHN0dWRlbnRJZCkgewogICAgICByZXR1cm4gYWN0aXZlQXNzaWdubWVudCgpCiAgICAgICAgICAmJiBhc3NpZ25tZW50KCkucm9sZUlkID09ICdwYXJlbnQnCiAgICAgICAgICAmJiBzdHVkZW50SWQgaW4gYXNzaWdubWVudCgpLnN0dWRlbnRJZHM7CiAgICB9CgogICAgZnVuY3Rpb24gcmVzb3VyY2VTdHVkZW50SWQoKSB7CiAgICAgIHJldHVybiByZXNvdXJjZS5kYXRhLnN0dWRlbnRJZDsKICAgIH0KCiAgICBmdW5jdGlvbiByZXF1ZXN0U3R1ZGVudElkKCkgewogICAgICByZXR1cm4gcmVxdWVzdC5yZXNvdXJjZS5kYXRhLnN0dWRlbnRJZDsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gUkJBQyBhZG1pbmlzdHJhdGlvbgogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiAgICBtYXRjaCAvYXBwX3JvbGVzL3tyb2xlSWR9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgc2lnbmVkSW4oKTsKICAgICAgYWxsb3cgY3JlYXRlLCB1cGRhdGUsIGRlbGV0ZTogaWYgaXNTdXBlckFkbWluKCk7CiAgICB9CgogICAgbWF0Y2ggL3VzZXJfcm9sZXMve3VzZXJJZH0gewogICAgICBhbGxvdyByZWFkOiBpZiBzaWduZWRJbigpCiAgICAgICAgICAmJiAocmVxdWVzdC5hdXRoLnVpZCA9PSB1c2VySWQgfHwgaXNTdXBlckFkbWluKCkpOwoKICAgICAgYWxsb3cgY3JlYXRlLCB1cGRhdGUsIGRlbGV0ZTogaWYgaXNTdXBlckFkbWluKCk7CgogICAgICAvLyBDYW5vbmljYWwgaWRlbnRpdHkgcmVxdWlyZW1lbnQuCiAgICAgIGFsbG93IGNyZWF0ZSwgdXBkYXRlOiBpZiBpc1N1cGVyQWRtaW4oKQogICAgICAgICAgJiYgcmVxdWVzdC5yZXNvdXJjZS5kYXRhLnVzZXJJZCA9PSB1c2VySWQ7CiAgICB9CgogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgIC8vIENvcmUgYWNhZGVtaWMgZGlyZWN0b3JpZXMKICAgIC8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgogICAgbWF0Y2ggL3N0dWRlbnRzL3tzdHVkZW50SWR9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignc3R1ZGVudHNWaWV3JykKICAgICAgICAgIHx8IGlzTGlua2VkUGFyZW50U3R1ZGVudChzdHVkZW50SWQpOwogICAgICBhbGxvdyBjcmVhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ3N0dWRlbnRzQ3JlYXRlJyk7CiAgICAgIGFsbG93IHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbignc3R1ZGVudHNFZGl0Jyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignc3R1ZGVudHNEZWxldGUnKTsKICAgIH0KCiAgICBtYXRjaCAvdGVhY2hlcnMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ3RlYWNoZXJzVmlldycpOwogICAgICBhbGxvdyBjcmVhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ3RlYWNoZXJzQ3JlYXRlJyk7CiAgICAgIGFsbG93IHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbigndGVhY2hlcnNFZGl0Jyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbigndGVhY2hlcnNEZWxldGUnKTsKICAgIH0KCiAgICBtYXRjaCAvc3RhZmYve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ3N0YWZmVmlldycpOwogICAgICBhbGxvdyBjcmVhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ3N0YWZmQ3JlYXRlJyk7CiAgICAgIGFsbG93IHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbignc3RhZmZFZGl0Jyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignc3RhZmZEZWxldGUnKTsKICAgIH0KCiAgICBtYXRjaCAvY2xhc3Nlcy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignY2xhc3Nlc1ZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2NsYXNzZXNNYW5hZ2UnKTsKICAgIH0KCiAgICBtYXRjaCAvc2VjdGlvbnMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2NsYXNzZXNWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdjbGFzc2VzTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL3N1YmplY3RzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNBbnlQZXJtaXNzaW9uKCdjbGFzc2VzVmlldycsICd0aW1ldGFibGVWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdjbGFzc2VzTWFuYWdlJyk7CiAgICB9CgogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgIC8vIEF0dGVuZGFuY2UKICAgIC8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgogICAgbWF0Y2ggL2F0dGVuZGFuY2Uve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2F0dGVuZGFuY2VWaWV3JykKICAgICAgICAgIHx8ICgKICAgICAgICAgICAgYWN0aXZlQXNzaWdubWVudCgpCiAgICAgICAgICAgICYmIGFzc2lnbm1lbnQoKS5yb2xlSWQgPT0gJ3BhcmVudCcKICAgICAgICAgICAgJiYgcmVzb3VyY2VTdHVkZW50SWQoKSBpbiBhc3NpZ25tZW50KCkuc3R1ZGVudElkcwogICAgICAgICAgKTsKICAgICAgYWxsb3cgY3JlYXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdhdHRlbmRhbmNlTWFyaycpOwogICAgICBhbGxvdyB1cGRhdGUsIGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignYXR0ZW5kYW5jZUVkaXQnKTsKICAgIH0KCiAgICBtYXRjaCAvdGVhY2hlcl9hdHRlbmRhbmNlL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNBbnlQZXJtaXNzaW9uKCd0ZWFjaGVyc1ZpZXcnLCAnYXR0ZW5kYW5jZVZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2F0dGVuZGFuY2VFZGl0Jyk7CiAgICB9CgogICAgbWF0Y2ggL3N0YWZmX2F0dGVuZGFuY2Uve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc0FueVBlcm1pc3Npb24oJ3N0YWZmVmlldycsICdhdHRlbmRhbmNlVmlldycpOwogICAgICBhbGxvdyB3cml0ZTogaWYgaGFzUGVybWlzc2lvbignYXR0ZW5kYW5jZUVkaXQnKTsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gRmVlcwogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiAgICBtYXRjaCAvZmVlX3N0cnVjdHVyZXMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2ZlZXNWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdmZWVzTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL3N0dWRlbnRfZmVlX2Fzc2lnbm1lbnRzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdmZWVzVmlldycpCiAgICAgICAgICB8fCAoCiAgICAgICAgICAgIGFjdGl2ZUFzc2lnbm1lbnQoKQogICAgICAgICAgICAmJiBhc3NpZ25tZW50KCkucm9sZUlkID09ICdwYXJlbnQnCiAgICAgICAgICAgICYmIHJlc291cmNlU3R1ZGVudElkKCkgaW4gYXNzaWdubWVudCgpLnN0dWRlbnRJZHMKICAgICAgICAgICk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdmZWVzTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL21vbnRobHlfZmVlcy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignZmVlc1ZpZXcnKQogICAgICAgICAgfHwgKAogICAgICAgICAgICBhY3RpdmVBc3NpZ25tZW50KCkKICAgICAgICAgICAgJiYgYXNzaWdubWVudCgpLnJvbGVJZCA9PSAncGFyZW50JwogICAgICAgICAgICAmJiByZXNvdXJjZVN0dWRlbnRJZCgpIGluIGFzc2lnbm1lbnQoKS5zdHVkZW50SWRzCiAgICAgICAgICApOwogICAgICBhbGxvdyBjcmVhdGUsIHVwZGF0ZTogaWYgaGFzQW55UGVybWlzc2lvbignZmVlc01hbmFnZScsICdmZWVzQ29sbGVjdCcpOwogICAgICBhbGxvdyBkZWxldGU6IGlmIGhhc1Blcm1pc3Npb24oJ2ZlZXNNYW5hZ2UnKTsKICAgIH0KCiAgICBtYXRjaCAvc3R1ZGVudF9mZWVzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdmZWVzVmlldycpCiAgICAgICAgICB8fCAoCiAgICAgICAgICAgIGFjdGl2ZUFzc2lnbm1lbnQoKQogICAgICAgICAgICAmJiBhc3NpZ25tZW50KCkucm9sZUlkID09ICdwYXJlbnQnCiAgICAgICAgICAgICYmIHJlc291cmNlU3R1ZGVudElkKCkgaW4gYXNzaWdubWVudCgpLnN0dWRlbnRJZHMKICAgICAgICAgICk7CiAgICAgIGFsbG93IGNyZWF0ZSwgdXBkYXRlOiBpZiBoYXNBbnlQZXJtaXNzaW9uKCdmZWVzTWFuYWdlJywgJ2ZlZXNDb2xsZWN0Jyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignZmVlc01hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC9mZWVfcGF5bWVudHMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2ZlZXNWaWV3JykKICAgICAgICAgIHx8ICgKICAgICAgICAgICAgYWN0aXZlQXNzaWdubWVudCgpCiAgICAgICAgICAgICYmIGFzc2lnbm1lbnQoKS5yb2xlSWQgPT0gJ3BhcmVudCcKICAgICAgICAgICAgJiYgcmVzb3VyY2VTdHVkZW50SWQoKSBpbiBhc3NpZ25tZW50KCkuc3R1ZGVudElkcwogICAgICAgICAgKTsKICAgICAgYWxsb3cgY3JlYXRlLCB1cGRhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2ZlZXNDb2xsZWN0Jyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignZmVlc01hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC9mZWVfY2hhbGxhbnMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2ZlZXNWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNBbnlQZXJtaXNzaW9uKCdmZWVzTWFuYWdlJywgJ2ZlZXNDb2xsZWN0Jyk7CiAgICB9CgogICAgbWF0Y2ggL2ZlZV9yZWNlaXB0cy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignZmVlc1ZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc0FueVBlcm1pc3Npb24oJ2ZlZXNNYW5hZ2UnLCAnZmVlc0NvbGxlY3QnKTsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gRXhhbXMsIGRhdGUgc2hlZXRzIGFuZCByZXN1bHRzCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQoKICAgIG1hdGNoIC9leGFtcy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignZXhhbXNWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdleGFtc01hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC9leGFtX3N1YmplY3Rfc2V0dXBzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdleGFtc1ZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2V4YW1zTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL2V4YW1fbWFya3Mve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc0FueVBlcm1pc3Npb24oJ2V4YW1zVmlldycsICdyZXN1bHRzVmlldycpOwogICAgICBhbGxvdyBjcmVhdGUsIHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c0VudGVyJyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignZXhhbXNNYW5hZ2UnKTsKICAgIH0KCiAgICBtYXRjaCAvZXhhbV9kYXRlX3NoZWV0cy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbignZGF0ZVNoZWV0c1ZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2RhdGVTaGVldHNNYW5hZ2UnKTsKICAgIH0KCiAgICBtYXRjaCAvcmVzdWx0cy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c1ZpZXcnKQogICAgICAgICAgfHwgKAogICAgICAgICAgICBhY3RpdmVBc3NpZ25tZW50KCkKICAgICAgICAgICAgJiYgYXNzaWdubWVudCgpLnJvbGVJZCA9PSAncGFyZW50JwogICAgICAgICAgICAmJiByZXNvdXJjZVN0dWRlbnRJZCgpIGluIGFzc2lnbm1lbnQoKS5zdHVkZW50SWRzCiAgICAgICAgICApOwogICAgICBhbGxvdyBjcmVhdGUsIHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c0VudGVyJyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c1B1Ymxpc2gnKTsKICAgIH0KCiAgICBtYXRjaCAvcmVzdWx0X3NoZWV0cy97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c1ZpZXcnKQogICAgICAgICAgfHwgKAogICAgICAgICAgICBhY3RpdmVBc3NpZ25tZW50KCkKICAgICAgICAgICAgJiYgYXNzaWdubWVudCgpLnJvbGVJZCA9PSAncGFyZW50JwogICAgICAgICAgICAmJiByZXNvdXJjZVN0dWRlbnRJZCgpIGluIGFzc2lnbm1lbnQoKS5zdHVkZW50SWRzCiAgICAgICAgICApOwogICAgICBhbGxvdyBjcmVhdGUsIHVwZGF0ZTogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c0VudGVyJyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbigncmVzdWx0c1B1Ymxpc2gnKTsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gVGltZXRhYmxlIGFuZCBob21ld29yawogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiAgICBtYXRjaCAvdGltZXRhYmxlX2VudHJpZXMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ3RpbWV0YWJsZVZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ3RpbWV0YWJsZU1hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC90aW1ldGFibGVfY29uZmlndXJhdGlvbnMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ3RpbWV0YWJsZVZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ3RpbWV0YWJsZU1hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC90ZWFjaGVyX2F2YWlsYWJpbGl0eS97ZG9jdW1lbnQ9Kip9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbigndGltZXRhYmxlVmlldycpOwogICAgICBhbGxvdyB3cml0ZTogaWYgaGFzUGVybWlzc2lvbigndGltZXRhYmxlTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL2hvbWV3b3JrL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdob21ld29ya1ZpZXcnKTsKICAgICAgYWxsb3cgY3JlYXRlLCB1cGRhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2hvbWV3b3JrQ3JlYXRlJyk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignaG9tZXdvcmtSZXZpZXcnKTsKICAgIH0KCiAgICBtYXRjaCAvaG9tZXdvcmtfc3VibWlzc2lvbnMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ2hvbWV3b3JrVmlldycpCiAgICAgICAgICB8fCAoCiAgICAgICAgICAgIGFjdGl2ZUFzc2lnbm1lbnQoKQogICAgICAgICAgICAmJiBhc3NpZ25tZW50KCkucm9sZUlkID09ICdwYXJlbnQnCiAgICAgICAgICAgICYmIHJlc291cmNlU3R1ZGVudElkKCkgaW4gYXNzaWdubWVudCgpLnN0dWRlbnRJZHMKICAgICAgICAgICk7CiAgICAgIGFsbG93IGNyZWF0ZTogaWYgc2lnbmVkSW4oKQogICAgICAgICAgJiYgKAogICAgICAgICAgICByZXF1ZXN0LmF1dGgudWlkID09IHJlcXVlc3QucmVzb3VyY2UuZGF0YS5zdWJtaXR0ZWRCeVVzZXJJZAogICAgICAgICAgICB8fCBoYXNQZXJtaXNzaW9uKCdob21ld29ya0NyZWF0ZScpCiAgICAgICAgICApOwogICAgICBhbGxvdyB1cGRhdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2hvbWV3b3JrUmV2aWV3JykKICAgICAgICAgIHx8ICgKICAgICAgICAgICAgc2lnbmVkSW4oKQogICAgICAgICAgICAmJiByZXF1ZXN0LmF1dGgudWlkID09IHJlc291cmNlLmRhdGEuc3VibWl0dGVkQnlVc2VySWQKICAgICAgICAgICk7CiAgICAgIGFsbG93IGRlbGV0ZTogaWYgaGFzUGVybWlzc2lvbignaG9tZXdvcmtSZXZpZXcnKTsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gTm90aWNlcyBhbmQgY2FsZW5kYXIKICAgIC8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgogICAgbWF0Y2ggL25vdGljZXMve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ25vdGljZXNWaWV3Jyk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdub3RpY2VzTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL25vdGljZV9yZWNlaXB0cy97cmVjZWlwdElkfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIGhhc1Blcm1pc3Npb24oJ25vdGljZXNNYW5hZ2UnKQogICAgICAgICAgfHwgKAogICAgICAgICAgICBzaWduZWRJbigpCiAgICAgICAgICAgICYmIHJlc291cmNlLmRhdGEucmVjaXBpZW50SWQgPT0gcmVxdWVzdC5hdXRoLnVpZAogICAgICAgICAgKTsKICAgICAgYWxsb3cgY3JlYXRlLCB1cGRhdGU6IGlmIHNpZ25lZEluKCkKICAgICAgICAgICYmIHJlcXVlc3QucmVzb3VyY2UuZGF0YS5yZWNpcGllbnRJZCA9PSByZXF1ZXN0LmF1dGgudWlkOwogICAgICBhbGxvdyBkZWxldGU6IGlmIGhhc1Blcm1pc3Npb24oJ25vdGljZXNNYW5hZ2UnKTsKICAgIH0KCiAgICBtYXRjaCAvYWNhZGVtaWNfY2FsZW5kYXJfZXZlbnRzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdjYWxlbmRhclZpZXcnKTsKICAgICAgYWxsb3cgd3JpdGU6IGlmIGhhc1Blcm1pc3Npb24oJ2NhbGVuZGFyTWFuYWdlJyk7CiAgICB9CgogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KICAgIC8vIFBhcmVudCBwb3J0YWwKICAgIC8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCgogICAgbWF0Y2ggL3BhcmVudF9hY2NvdW50cy97cGFyZW50SWR9IHsKICAgICAgYWxsb3cgcmVhZDogaWYgaGFzUGVybWlzc2lvbigncGFyZW50c1ZpZXcnKQogICAgICAgICAgfHwgb3duc1BhcmVudEFjY291bnQocGFyZW50SWQpOwogICAgICBhbGxvdyBjcmVhdGUsIHVwZGF0ZSwgZGVsZXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdwYXJlbnRzTWFuYWdlJyk7CiAgICB9CgogICAgbWF0Y2ggL3BhcmVudF9ub3RpZmljYXRpb25zL3tub3RpZmljYXRpb25JZH0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdwYXJlbnRzTWFuYWdlJykKICAgICAgICAgIHx8ICgKICAgICAgICAgICAgc2lnbmVkSW4oKQogICAgICAgICAgICAmJiByZXNvdXJjZS5kYXRhLnBhcmVudEF1dGhVc2VySWQgPT0gcmVxdWVzdC5hdXRoLnVpZAogICAgICAgICAgKTsKICAgICAgYWxsb3cgY3JlYXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdwYXJlbnRzTWFuYWdlJyk7CiAgICAgIGFsbG93IHVwZGF0ZSwgZGVsZXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdwYXJlbnRzTWFuYWdlJykKICAgICAgICAgIHx8ICgKICAgICAgICAgICAgc2lnbmVkSW4oKQogICAgICAgICAgICAmJiByZXNvdXJjZS5kYXRhLnBhcmVudEF1dGhVc2VySWQgPT0gcmVxdWVzdC5hdXRoLnVpZAogICAgICAgICAgKTsKICAgIH0KCiAgICAvLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogICAgLy8gQ29uZmlndXJhdGlvbiwgcmVwb3J0aW5nIGFuZCBhdWRpdAogICAgLy8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCiAgICBtYXRjaCAvYWNhZGVtaWNfeWVhcl9jb25maWcve2RvY3VtZW50PSoqfSB7CiAgICAgIGFsbG93IHJlYWQ6IGlmIHNpZ25lZEluKCk7CiAgICAgIGFsbG93IHdyaXRlOiBpZiBoYXNQZXJtaXNzaW9uKCdzZXR0aW5nc01hbmFnZScpOwogICAgfQoKICAgIG1hdGNoIC9hdWRpdF9sb2dzL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkOiBpZiBoYXNQZXJtaXNzaW9uKCdhdWRpdExvZ3NWaWV3Jyk7CiAgICAgIGFsbG93IGNyZWF0ZTogaWYgc2lnbmVkSW4oKTsKICAgICAgYWxsb3cgdXBkYXRlLCBkZWxldGU6IGlmIGZhbHNlOwogICAgfQoKICAgIC8vIEtub3duIHN1cHBvcnRpbmcgY29sbGVjdGlvbnMgbm90IHlldCBtYXBwZWQgdG8gYSBkZWRpY2F0ZWQKICAgIC8vIHBlcm1pc3Npb24gdXNlIGF1dGhlbnRpY2F0ZWQgYWNjZXNzIGR1cmluZyB0aGlzIHN0YWdlZCByZWxlYXNlLgogICAgbWF0Y2ggL3tkb2N1bWVudD0qKn0gewogICAgICBhbGxvdyByZWFkLCB3cml0ZTogaWYgc2lnbmVkSW4oKQogICAgICAgICAgJiYgKAogICAgICAgICAgICBpc1N1cGVyQWRtaW4oKQogICAgICAgICAgICB8fCBoYXNQZXJtaXNzaW9uKCdzZXR0aW5nc01hbmFnZScpCiAgICAgICAgICApOwogICAgfQogIH0KfQo='
    'firestore.indexes.json' = 'ewogICJpbmRleGVzIjogW10sCiAgImZpZWxkT3ZlcnJpZGVzIjogW10KfQo='
    'lib/features/access_control/data/services/access_control_migration_service.dart' = 'aW1wb3J0ICdwYWNrYWdlOmNsb3VkX2ZpcmVzdG9yZS9jbG91ZF9maXJlc3RvcmUuZGFydCc7CgpjbGFzcyBBY2Nlc3NDb250cm9sTWlncmF0aW9uUmVzdWx0IHsKICBjb25zdCBBY2Nlc3NDb250cm9sTWlncmF0aW9uUmVzdWx0KHsKICAgIHJlcXVpcmVkIHRoaXMuc2Nhbm5lZCwKICAgIHJlcXVpcmVkIHRoaXMubWlncmF0ZWQsCiAgICByZXF1aXJlZCB0aGlzLnNraXBwZWQsCiAgICByZXF1aXJlZCB0aGlzLmRlbGV0ZWRMZWdhY3ksCiAgfSk7CgogIGZpbmFsIGludCBzY2FubmVkOwogIGZpbmFsIGludCBtaWdyYXRlZDsKICBmaW5hbCBpbnQgc2tpcHBlZDsKICBmaW5hbCBpbnQgZGVsZXRlZExlZ2FjeTsKfQoKY2xhc3MgQWNjZXNzQ29udHJvbE1pZ3JhdGlvblNlcnZpY2UgewogIGNvbnN0IEFjY2Vzc0NvbnRyb2xNaWdyYXRpb25TZXJ2aWNlKHRoaXMuX2ZpcmVzdG9yZSk7CgogIGZpbmFsIEZpcmViYXNlRmlyZXN0b3JlIF9maXJlc3RvcmU7CgogIEZ1dHVyZTxBY2Nlc3NDb250cm9sTWlncmF0aW9uUmVzdWx0PgogICAgICBtaWdyYXRlVXNlclJvbGVEb2N1bWVudHNUb1VpZElkcygpIGFzeW5jIHsKICAgIGZpbmFsIGNvbGxlY3Rpb24gPSBfZmlyZXN0b3JlLmNvbGxlY3Rpb24oJ3VzZXJfcm9sZXMnKTsKICAgIGZpbmFsIHNuYXBzaG90ID0gYXdhaXQgY29sbGVjdGlvbi5nZXQoKTsKCiAgICB2YXIgbWlncmF0ZWQgPSAwOwogICAgdmFyIHNraXBwZWQgPSAwOwogICAgdmFyIGRlbGV0ZWRMZWdhY3kgPSAwOwoKICAgIGZvciAoZmluYWwgZG9jdW1lbnQgaW4gc25hcHNob3QuZG9jcykgewogICAgICBmaW5hbCBkYXRhID0gZG9jdW1lbnQuZGF0YSgpOwogICAgICBmaW5hbCB1c2VySWQgPSBkYXRhWyd1c2VySWQnXT8udG9TdHJpbmcoKS50cmltKCkgPz8gJyc7CgogICAgICBpZiAodXNlcklkLmlzRW1wdHkpIHsKICAgICAgICBza2lwcGVkKys7CiAgICAgICAgY29udGludWU7CiAgICAgIH0KCiAgICAgIGlmIChkb2N1bWVudC5pZCA9PSB1c2VySWQpIHsKICAgICAgICBza2lwcGVkKys7CiAgICAgICAgY29udGludWU7CiAgICAgIH0KCiAgICAgIGF3YWl0IF9maXJlc3RvcmUucnVuVHJhbnNhY3Rpb24oKHRyYW5zYWN0aW9uKSBhc3luYyB7CiAgICAgICAgZmluYWwgY2Fub25pY2FsID0gY29sbGVjdGlvbi5kb2ModXNlcklkKTsKICAgICAgICBmaW5hbCBjYW5vbmljYWxTbmFwc2hvdCA9IGF3YWl0IHRyYW5zYWN0aW9uLmdldChjYW5vbmljYWwpOwoKICAgICAgICBpZiAoIWNhbm9uaWNhbFNuYXBzaG90LmV4aXN0cykgewogICAgICAgICAgdHJhbnNhY3Rpb24uc2V0KGNhbm9uaWNhbCwgZGF0YSk7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgIHRyYW5zYWN0aW9uLnNldChjYW5vbmljYWwsIGRhdGEsIFNldE9wdGlvbnMobWVyZ2U6IHRydWUpKTsKICAgICAgICB9CgogICAgICAgIHRyYW5zYWN0aW9uLmRlbGV0ZShkb2N1bWVudC5yZWZlcmVuY2UpOwogICAgICB9KTsKCiAgICAgIG1pZ3JhdGVkKys7CiAgICAgIGRlbGV0ZWRMZWdhY3krKzsKICAgIH0KCiAgICByZXR1cm4gQWNjZXNzQ29udHJvbE1pZ3JhdGlvblJlc3VsdCgKICAgICAgc2Nhbm5lZDogc25hcHNob3QuZG9jcy5sZW5ndGgsCiAgICAgIG1pZ3JhdGVkOiBtaWdyYXRlZCwKICAgICAgc2tpcHBlZDogc2tpcHBlZCwKICAgICAgZGVsZXRlZExlZ2FjeTogZGVsZXRlZExlZ2FjeSwKICAgICk7CiAgfQoKICBGdXR1cmU8TGlzdDxTdHJpbmc+PiB2YWxpZGF0ZVByb2R1Y3Rpb25SZWFkaW5lc3MoKSBhc3luYyB7CiAgICBmaW5hbCBpc3N1ZXMgPSA8U3RyaW5nPltdOwoKICAgIGZpbmFsIHJvbGVzID0gYXdhaXQgX2ZpcmVzdG9yZS5jb2xsZWN0aW9uKCdhcHBfcm9sZXMnKS5nZXQoKTsKICAgIGlmIChyb2xlcy5kb2NzLmlzRW1wdHkpIHsKICAgICAgaXNzdWVzLmFkZCgnTm8gYXBwX3JvbGVzIGRvY3VtZW50cyBmb3VuZC4nKTsKICAgIH0KCiAgICBmaW5hbCBhc3NpZ25tZW50cyA9CiAgICAgICAgYXdhaXQgX2ZpcmVzdG9yZS5jb2xsZWN0aW9uKCd1c2VyX3JvbGVzJykuZ2V0KCk7CgogICAgaWYgKGFzc2lnbm1lbnRzLmRvY3MuaXNFbXB0eSkgewogICAgICBpc3N1ZXMuYWRkKCdObyB1c2VyX3JvbGVzIGFzc2lnbm1lbnRzIGZvdW5kLicpOwogICAgfQoKICAgIGZvciAoZmluYWwgZG9jdW1lbnQgaW4gYXNzaWdubWVudHMuZG9jcykgewogICAgICBmaW5hbCBkYXRhID0gZG9jdW1lbnQuZGF0YSgpOwogICAgICBmaW5hbCB1c2VySWQgPSBkYXRhWyd1c2VySWQnXT8udG9TdHJpbmcoKS50cmltKCkgPz8gJyc7CiAgICAgIGZpbmFsIHJvbGVJZCA9IGRhdGFbJ3JvbGVJZCddPy50b1N0cmluZygpLnRyaW0oKSA/PyAnJzsKCiAgICAgIGlmICh1c2VySWQuaXNFbXB0eSkgewogICAgICAgIGlzc3Vlcy5hZGQoCiAgICAgICAgICAnQXNzaWdubWVudCAke2RvY3VtZW50LmlkfSBoYXMgbm8gRmlyZWJhc2UgdXNlcklkLicsCiAgICAgICAgKTsKICAgICAgfSBlbHNlIGlmIChkb2N1bWVudC5pZCAhPSB1c2VySWQpIHsKICAgICAgICBpc3N1ZXMuYWRkKAogICAgICAgICAgJ0Fzc2lnbm1lbnQgJHtkb2N1bWVudC5pZH0gaXMgbm90IHN0b3JlZCBhcyB1c2VyX3JvbGVzLyR1c2VySWQuJywKICAgICAgICApOwogICAgICB9CgogICAgICBpZiAocm9sZUlkLmlzRW1wdHkpIHsKICAgICAgICBpc3N1ZXMuYWRkKCdBc3NpZ25tZW50ICR7ZG9jdW1lbnQuaWR9IGhhcyBubyByb2xlSWQuJyk7CiAgICAgIH0gZWxzZSB7CiAgICAgICAgZmluYWwgcm9sZSA9CiAgICAgICAgICAgIGF3YWl0IF9maXJlc3RvcmUuY29sbGVjdGlvbignYXBwX3JvbGVzJykuZG9jKHJvbGVJZCkuZ2V0KCk7CiAgICAgICAgaWYgKCFyb2xlLmV4aXN0cykgewogICAgICAgICAgaXNzdWVzLmFkZCgKICAgICAgICAgICAgJ0Fzc2lnbm1lbnQgJHtkb2N1bWVudC5pZH0gcmVmZXJlbmNlcyBtaXNzaW5nIHJvbGUgJHJvbGVJZC4nLAogICAgICAgICAgKTsKICAgICAgICB9CiAgICAgIH0KICAgIH0KCiAgICBmaW5hbCBzdXBlckFkbWlucyA9IGFzc2lnbm1lbnRzLmRvY3Mud2hlcmUoKGRvY3VtZW50KSB7CiAgICAgIGZpbmFsIGRhdGEgPSBkb2N1bWVudC5kYXRhKCk7CiAgICAgIHJldHVybiBkYXRhWydyb2xlSWQnXSA9PSAnc3VwZXJfYWRtaW4nICYmCiAgICAgICAgICBkYXRhWydpc0FjdGl2ZSddID09IHRydWU7CiAgICB9KTsKCiAgICBpZiAoc3VwZXJBZG1pbnMuaXNFbXB0eSkgewogICAgICBpc3N1ZXMuYWRkKAogICAgICAgICdObyBhY3RpdmUgU3VwZXIgQWRtaW4gYXNzaWdubWVudCBmb3VuZC4gRG8gbm90IGRlcGxveSBydWxlcy4nLAogICAgICApOwogICAgfQoKICAgIHJldHVybiBpc3N1ZXM7CiAgfQp9Cg=='
    'lib/features/access_control/presentation/pages/access_control_production_readiness_page.dart' = 'aW1wb3J0ICdwYWNrYWdlOmNsb3VkX2ZpcmVzdG9yZS9jbG91ZF9maXJlc3RvcmUuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnOwoKaW1wb3J0ICcuLi8uLi8uLi8uLi9jb3JlL2RpL3NlcnZpY2VfbG9jYXRvci5kYXJ0JzsKaW1wb3J0ICcuLi8uLi9kYXRhL3NlcnZpY2VzL2FjY2Vzc19jb250cm9sX21pZ3JhdGlvbl9zZXJ2aWNlLmRhcnQnOwoKY2xhc3MgQWNjZXNzQ29udHJvbFByb2R1Y3Rpb25SZWFkaW5lc3NQYWdlCiAgICBleHRlbmRzIFN0YXRlZnVsV2lkZ2V0IHsKICBjb25zdCBBY2Nlc3NDb250cm9sUHJvZHVjdGlvblJlYWRpbmVzc1BhZ2Uoe3N1cGVyLmtleX0pOwoKICBAb3ZlcnJpZGUKICBTdGF0ZTxBY2Nlc3NDb250cm9sUHJvZHVjdGlvblJlYWRpbmVzc1BhZ2U+IGNyZWF0ZVN0YXRlKCkgPT4KICAgICAgX0FjY2Vzc0NvbnRyb2xQcm9kdWN0aW9uUmVhZGluZXNzUGFnZVN0YXRlKCk7Cn0KCmNsYXNzIF9BY2Nlc3NDb250cm9sUHJvZHVjdGlvblJlYWRpbmVzc1BhZ2VTdGF0ZQogICAgZXh0ZW5kcyBTdGF0ZTxBY2Nlc3NDb250cm9sUHJvZHVjdGlvblJlYWRpbmVzc1BhZ2U+IHsKICBsYXRlIGZpbmFsIEFjY2Vzc0NvbnRyb2xNaWdyYXRpb25TZXJ2aWNlIF9taWdyYXRpb25TZXJ2aWNlOwogIGJvb2wgX2J1c3kgPSBmYWxzZTsKICBMaXN0PFN0cmluZz4/IF9pc3N1ZXM7CiAgU3RyaW5nPyBfbWVzc2FnZTsKCiAgQG92ZXJyaWRlCiAgdm9pZCBpbml0U3RhdGUoKSB7CiAgICBzdXBlci5pbml0U3RhdGUoKTsKICAgIF9taWdyYXRpb25TZXJ2aWNlID0gQWNjZXNzQ29udHJvbE1pZ3JhdGlvblNlcnZpY2UoCiAgICAgIHNsPEZpcmViYXNlRmlyZXN0b3JlPigpLAogICAgKTsKICB9CgogIEZ1dHVyZTx2b2lkPiBfbWlncmF0ZSgpIGFzeW5jIHsKICAgIHNldFN0YXRlKCgpIHsKICAgICAgX2J1c3kgPSB0cnVlOwogICAgICBfbWVzc2FnZSA9IG51bGw7CiAgICB9KTsKCiAgICB0cnkgewogICAgICBmaW5hbCByZXN1bHQgPSBhd2FpdCBfbWlncmF0aW9uU2VydmljZQogICAgICAgICAgLm1pZ3JhdGVVc2VyUm9sZURvY3VtZW50c1RvVWlkSWRzKCk7CgogICAgICBpZiAoIW1vdW50ZWQpIHJldHVybjsKCiAgICAgIHNldFN0YXRlKCgpIHsKICAgICAgICBfbWVzc2FnZSA9CiAgICAgICAgICAgICdTY2FubmVkICR7cmVzdWx0LnNjYW5uZWR9OyBtaWdyYXRlZCAke3Jlc3VsdC5taWdyYXRlZH07ICcKICAgICAgICAgICAgJ3NraXBwZWQgJHtyZXN1bHQuc2tpcHBlZH07IHJlbW92ZWQgbGVnYWN5ICcKICAgICAgICAgICAgJyR7cmVzdWx0LmRlbGV0ZWRMZWdhY3l9Lic7CiAgICAgIH0pOwoKICAgICAgYXdhaXQgX3ZhbGlkYXRlKCk7CiAgICB9IGNhdGNoIChlcnJvcikgewogICAgICBpZiAoIW1vdW50ZWQpIHJldHVybjsKICAgICAgc2V0U3RhdGUoKCkgPT4gX21lc3NhZ2UgPSAnTWlncmF0aW9uIGZhaWxlZDogJGVycm9yJyk7CiAgICB9IGZpbmFsbHkgewogICAgICBpZiAobW91bnRlZCkgc2V0U3RhdGUoKCkgPT4gX2J1c3kgPSBmYWxzZSk7CiAgICB9CiAgfQoKICBGdXR1cmU8dm9pZD4gX3ZhbGlkYXRlKCkgYXN5bmMgewogICAgc2V0U3RhdGUoKCkgewogICAgICBfYnVzeSA9IHRydWU7CiAgICAgIF9tZXNzYWdlID0gbnVsbDsKICAgIH0pOwoKICAgIHRyeSB7CiAgICAgIGZpbmFsIGlzc3VlcyA9CiAgICAgICAgICBhd2FpdCBfbWlncmF0aW9uU2VydmljZS52YWxpZGF0ZVByb2R1Y3Rpb25SZWFkaW5lc3MoKTsKCiAgICAgIGlmICghbW91bnRlZCkgcmV0dXJuOwoKICAgICAgc2V0U3RhdGUoKCkgewogICAgICAgIF9pc3N1ZXMgPSBpc3N1ZXM7CiAgICAgICAgX21lc3NhZ2UgPSBpc3N1ZXMuaXNFbXB0eQogICAgICAgICAgICA/ICdQcm9kdWN0aW9uIHJlYWRpbmVzcyB2YWxpZGF0aW9uIHBhc3NlZC4nCiAgICAgICAgICAgIDogJ1Jlc29sdmUgYWxsIGlzc3VlcyBiZWZvcmUgZGVwbG95aW5nIEZpcmVzdG9yZSBydWxlcy4nOwogICAgICB9KTsKICAgIH0gY2F0Y2ggKGVycm9yKSB7CiAgICAgIGlmICghbW91bnRlZCkgcmV0dXJuOwogICAgICBzZXRTdGF0ZSgoKSA9PiBfbWVzc2FnZSA9ICdWYWxpZGF0aW9uIGZhaWxlZDogJGVycm9yJyk7CiAgICB9IGZpbmFsbHkgewogICAgICBpZiAobW91bnRlZCkgc2V0U3RhdGUoKCkgPT4gX2J1c3kgPSBmYWxzZSk7CiAgICB9CiAgfQoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIGZpbmFsIGlzc3VlcyA9IF9pc3N1ZXM7CgogICAgcmV0dXJuIFNjYWZmb2xkKAogICAgICBhcHBCYXI6IEFwcEJhcigKICAgICAgICB0aXRsZTogY29uc3QgVGV4dCgnQWNjZXNzIENvbnRyb2wgUHJvZHVjdGlvbiBSZWFkaW5lc3MnKSwKICAgICAgKSwKICAgICAgYm9keTogTGlzdFZpZXcoCiAgICAgICAgcGFkZGluZzogY29uc3QgRWRnZUluc2V0cy5hbGwoMjApLAogICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICBDYXJkKAogICAgICAgICAgICBjaGlsZDogUGFkZGluZygKICAgICAgICAgICAgICBwYWRkaW5nOiBjb25zdCBFZGdlSW5zZXRzLmFsbCgxNiksCiAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoCiAgICAgICAgICAgICAgICAnUnVuIG1pZ3JhdGlvbiBmaXJzdC4gVGhlbiB2YWxpZGF0ZS4gRGVwbG95ICcKICAgICAgICAgICAgICAgICdmaXJlc3RvcmUucnVsZXMgb25seSB3aGVuIHZhbGlkYXRpb24gcGFzc2VzIGFuZCBhbiAnCiAgICAgICAgICAgICAgICAnYWN0aXZlIFN1cGVyIEFkbWluIGFzc2lnbm1lbnQgZXhpc3RzLicsCiAgICAgICAgICAgICAgICBzdHlsZTogVGhlbWUub2YoY29udGV4dCkudGV4dFRoZW1lLmJvZHlMYXJnZSwKICAgICAgICAgICAgICApLAogICAgICAgICAgICApLAogICAgICAgICAgKSwKICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTIpLAogICAgICAgICAgV3JhcCgKICAgICAgICAgICAgc3BhY2luZzogMTAsCiAgICAgICAgICAgIHJ1blNwYWNpbmc6IDEwLAogICAgICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICAgIEZpbGxlZEJ1dHRvbi5pY29uKAogICAgICAgICAgICAgICAgb25QcmVzc2VkOiBfYnVzeSA/IG51bGwgOiBfbWlncmF0ZSwKICAgICAgICAgICAgICAgIGljb246IGNvbnN0IEljb24oSWNvbnMuc3luY19hbHQpLAogICAgICAgICAgICAgICAgbGFiZWw6IGNvbnN0IFRleHQoJ01pZ3JhdGUgVXNlciBSb2xlcyB0byBVSUQgSURzJyksCiAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICBGaWxsZWRCdXR0b24udG9uYWxJY29uKAogICAgICAgICAgICAgICAgb25QcmVzc2VkOiBfYnVzeSA/IG51bGwgOiBfdmFsaWRhdGUsCiAgICAgICAgICAgICAgICBpY29uOiBjb25zdCBJY29uKEljb25zLnZlcmlmaWVkX291dGxpbmVkKSwKICAgICAgICAgICAgICAgIGxhYmVsOiBjb25zdCBUZXh0KCdWYWxpZGF0ZSBQcm9kdWN0aW9uIFJlYWRpbmVzcycpLAogICAgICAgICAgICAgICksCiAgICAgICAgICAgIF0sCiAgICAgICAgICApLAogICAgICAgICAgaWYgKF9idXN5KSAuLi5bCiAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTYpLAogICAgICAgICAgICBjb25zdCBMaW5lYXJQcm9ncmVzc0luZGljYXRvcigpLAogICAgICAgICAgXSwKICAgICAgICAgIGlmIChfbWVzc2FnZSAhPSBudWxsKSAuLi5bCiAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogMTYpLAogICAgICAgICAgICBDYXJkKAogICAgICAgICAgICAgIGNoaWxkOiBQYWRkaW5nKAogICAgICAgICAgICAgICAgcGFkZGluZzogY29uc3QgRWRnZUluc2V0cy5hbGwoMTYpLAogICAgICAgICAgICAgICAgY2hpbGQ6IFRleHQoX21lc3NhZ2UhKSwKICAgICAgICAgICAgICApLAogICAgICAgICAgICApLAogICAgICAgICAgXSwKICAgICAgICAgIGlmIChpc3N1ZXMgIT0gbnVsbCkgLi4uWwogICAgICAgICAgICBjb25zdCBTaXplZEJveChoZWlnaHQ6IDE2KSwKICAgICAgICAgICAgVGV4dCgKICAgICAgICAgICAgICBpc3N1ZXMuaXNFbXB0eSA/ICdWYWxpZGF0aW9uIFBhc3NlZCcgOiAnQmxvY2tpbmcgSXNzdWVzJywKICAgICAgICAgICAgICBzdHlsZTogVGhlbWUub2YoY29udGV4dCkKICAgICAgICAgICAgICAgICAgLnRleHRUaGVtZQogICAgICAgICAgICAgICAgICAudGl0bGVMYXJnZQogICAgICAgICAgICAgICAgICA/LmNvcHlXaXRoKGZvbnRXZWlnaHQ6IEZvbnRXZWlnaHQuYm9sZCksCiAgICAgICAgICAgICksCiAgICAgICAgICAgIGNvbnN0IFNpemVkQm94KGhlaWdodDogOCksCiAgICAgICAgICAgIGlmIChpc3N1ZXMuaXNFbXB0eSkKICAgICAgICAgICAgICBjb25zdCBDYXJkKAogICAgICAgICAgICAgICAgY2hpbGQ6IExpc3RUaWxlKAogICAgICAgICAgICAgICAgICBsZWFkaW5nOiBJY29uKEljb25zLmNoZWNrX2NpcmNsZV9vdXRsaW5lKSwKICAgICAgICAgICAgICAgICAgdGl0bGU6IFRleHQoCiAgICAgICAgICAgICAgICAgICAgJ1VJRCByb2xlIGRvY3VtZW50cyBhbmQgYWN0aXZlIFN1cGVyIEFkbWluIHZlcmlmaWVkLicsCiAgICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICkKICAgICAgICAgICAgZWxzZQogICAgICAgICAgICAgIGZvciAoZmluYWwgaXNzdWUgaW4gaXNzdWVzKQogICAgICAgICAgICAgICAgQ2FyZCgKICAgICAgICAgICAgICAgICAgY2hpbGQ6IExpc3RUaWxlKAogICAgICAgICAgICAgICAgICAgIGxlYWRpbmc6IGNvbnN0IEljb24oSWNvbnMuZXJyb3Jfb3V0bGluZSksCiAgICAgICAgICAgICAgICAgICAgdGl0bGU6IFRleHQoaXNzdWUpLAogICAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgKSwKICAgICAgICAgIF0sCiAgICAgICAgXSwKICAgICAgKSwKICAgICk7CiAgfQp9Cg=='
    'docs/roles_permissions_phase4_production_deployment.md' = 'IyBSb2xlcyAmIFBlcm1pc3Npb25zIFBoYXNlIDQg4oCUIFByb2R1Y3Rpb24gRGVwbG95bWVudAoKIyMgQ3JpdGljYWwgZGVwbG95bWVudCBvcmRlcgoKMS4gT3BlbiAqKlJvbGVzICYgUGVybWlzc2lvbnMqKi4KMi4gQ3JlYXRlIGRlZmF1bHQgcm9sZXMgaWYgdGhleSBkbyBub3QgYWxyZWFkeSBleGlzdC4KMy4gT3BlbiAqKlVzZXIgQXNzaWdubWVudHMqKi4KNC4gQXNzaWduIHRoZSBjdXJyZW50bHkgbG9nZ2VkLWluIEZpcmViYXNlIHVzZXIgdGhlICoqU3VwZXIgQWRtaW4qKiByb2xlLgo1LiBPcGVuICoqUHJvZHVjdGlvbiBSZWFkaW5lc3MqKi4KNi4gUnVuICoqTWlncmF0ZSBVc2VyIFJvbGVzIHRvIFVJRCBJRHMqKi4KNy4gUnVuICoqVmFsaWRhdGUgUHJvZHVjdGlvbiBSZWFkaW5lc3MqKi4KOC4gQ29udGludWUgb25seSB3aGVuIHZhbGlkYXRpb24gcmVwb3J0cyBubyBibG9ja2luZyBpc3N1ZXMuCjkuIEJhY2sgdXAgRmlyZXN0b3JlLgoxMC4gRGVwbG95IHRoZSBzdGFnZWQgcnVsZXM6CgpgYGBwb3dlcnNoZWxsCmZpcmViYXNlIGRlcGxveSAtLW9ubHkgZmlyZXN0b3JlOnJ1bGVzCmBgYAoKIyMgV2h5IG1pZ3JhdGlvbiBpcyBtYW5kYXRvcnkKCkZpcmVzdG9yZSBTZWN1cml0eSBSdWxlcyBjYW5ub3QgcXVlcnkgYHVzZXJfcm9sZXNgIGJ5IHRoZSBgdXNlcklkYCBmaWVsZC4KVGhlIGF1dGhlbnRpY2F0ZWQgdXNlcidzIGFzc2lnbm1lbnQgbXVzdCBiZSBzdG9yZWQgYXQ6CgpgYGB0ZXh0CnVzZXJfcm9sZXMve0ZpcmViYXNlQXV0aFVJRH0KYGBgCgpUaGUgbWlncmF0aW9uIHV0aWxpdHkgY29udmVydHMgbGVnYWN5IHJhbmRvbSBkb2N1bWVudCBJRHMgdG8gdGhpcyBjYW5vbmljYWwKZm9ybWF0IGJlZm9yZSBydWxlcyBhcmUgZGVwbG95ZWQuCgojIyBSb2xsYmFjawoKVGhlIFBoYXNlIDQgaW5zdGFsbGVyIGNyZWF0ZXMgYSBsb2NhbCBiYWNrdXAuIElmIGRlcGxveWVkIHJ1bGVzIGJsb2NrIHZhbGlkCnRyYWZmaWMsIHJlc3RvcmUgdGhlIHByaW9yIHJ1bGVzIGluIEZpcmViYXNlIENvbnNvbGUgb3IgZGVwbG95IHRoZSBiYWNrdXAKcnVsZXMgZmlsZS4gRG8gbm90IGRlbGV0ZSB0aGUgYWN0aXZlIFN1cGVyIEFkbWluIGFzc2lnbm1lbnQuCgojIyBTZWN1cml0eSBzY29wZQoKVGhlIHN0YWdlZCBydWxlcyBjb3ZlciByb2xlIGFkbWluaXN0cmF0aW9uLCBzdHVkZW50cywgdGVhY2hlcnMsIHN0YWZmLAphdHRlbmRhbmNlLCBmZWVzLCBleGFtcywgZGF0ZSBzaGVldHMsIHJlc3VsdHMsIHRpbWV0YWJsZSwgaG9tZXdvcmssIG5vdGljZXMsCmFjYWRlbWljIGNhbGVuZGFyLCBwYXJlbnQgYWNjZXNzLCBub3RpZmljYXRpb25zLCBjb25maWd1cmF0aW9uIGFuZCBhdWRpdApsb2dzLgoKQ29sbGVjdGlvbiBuYW1lcyB0aGF0IGRvIG5vdCB5ZXQgaGF2ZSBhIGRlZGljYXRlZCBwZXJtaXNzaW9uIG1hcHBpbmcgZmFsbApiYWNrIHRvIFN1cGVyIEFkbWluIG9yIFNldHRpbmdzIE1hbmFnZXIgYWNjZXNzLiBUZXN0IGV2ZXJ5IHByb2R1Y3Rpb24Kd29ya2Zsb3cgYWdhaW5zdCB0aGUgRmlyZWJhc2UgRW11bGF0b3IgYmVmb3JlIHB1YmxpYyBkZXBsb3ltZW50Lgo='
}
$firebaseJson = 'firebase.json'
$rolesPage = 'lib/features/access_control/presentation/pages/roles_permissions_page.dart'
$assignmentRepository = 'lib/features/access_control/data/repositories/user_role_assignment_repository_impl.dart'
$assignmentForm = 'lib/features/access_control/presentation/pages/user_role_assignment_form_page.dart'

foreach ($relativePath in (@(
    $firebaseJson,
    $rolesPage,
    $assignmentRepository,
    $assignmentForm
) + $payloads.Keys)) {
    Backup-ProjectFile -RelativePath $relativePath
}

foreach ($item in $payloads.GetEnumerator()) {
    $text = [Text.Encoding]::UTF8.GetString(
        [Convert]::FromBase64String($item.Value)
    )

    Write-ProjectFile `
        -RelativePath $item.Key `
        -Content $text
}

# Canonicalize all future assignments to user_roles/{FirebaseAuthUID}.
$content = Read-ProjectFile -RelativePath $assignmentRepository

$oldSave = @'
    await _service
        .collection(FirestorePaths.userRoleAssignments)
        .doc(assignment.id)
        .set(
          UserRoleAssignmentModel.fromEntity(assignment).toMap(),
        );
'@

$newSave = @'
    await _service
        .collection(FirestorePaths.userRoleAssignments)
        .doc(assignment.userId.trim())
        .set(
          UserRoleAssignmentModel.fromEntity(assignment).toMap(),
        );

    if (assignment.id != assignment.userId.trim()) {
      await _service
          .collection(FirestorePaths.userRoleAssignments)
          .doc(assignment.id)
          .delete();
    }
'@

if ($content.Contains($oldSave)) {
    $content = $content.Replace($oldSave, $newSave)
} elseif (-not $content.Contains('.doc(assignment.userId.trim())')) {
    throw 'User role save anchor not found.'
}

Write-ProjectFile `
    -RelativePath $assignmentRepository `
    -Content $content

# New assignments use the UID as their entity/document ID.
$content = Read-ProjectFile -RelativePath $assignmentForm

$oldId = @'
        id: old?.id ??
            sl<UserRoleAssignmentRepository>().generateId(),
'@

$newId = @'
        id: old?.id ?? _userId.text.trim(),
'@

if ($content.Contains($oldId)) {
    $content = $content.Replace($oldId, $newId)
} elseif (-not $content.Contains(
    'id: old?.id ?? _userId.text.trim()'
)) {
    throw 'User assignment ID anchor not found.'
}

Write-ProjectFile `
    -RelativePath $assignmentForm `
    -Content $content

# Add Production Readiness button.
$content = Read-ProjectFile -RelativePath $rolesPage

$content = Add-Import `
    -Content $content `
    -ImportLine "import 'access_control_production_readiness_page.dart';"

if (-not $content.Contains(
    'const AccessControlProductionReadinessPage()'
)) {
    $actionsAnchor = @'
        actions: [
'@

    $index = $content.IndexOf($actionsAnchor)

    if ($index -lt 0) {
        throw 'Roles page AppBar actions anchor not found.'
    }

    $insertIndex = $index + $actionsAnchor.Length

    $button = @'
          TextButton.icon(
            onPressed: () {
              Navigator.of(context).push<void>(
                MaterialPageRoute<void>(
                  builder: (_) =>
                      const AccessControlProductionReadinessPage(),
                ),
              );
            },
            icon: const Icon(Icons.security_outlined),
            label: const Text('Production Readiness'),
          ),
'@

    $content = $content.Insert($insertIndex, $button)
}

Write-ProjectFile -RelativePath $rolesPage -Content $content

# Preserve FlutterFire configuration and add Firestore deployment files.
$firebasePath = Join-Path $root $firebaseJson
$firebaseConfig = Get-Content $firebasePath -Raw | ConvertFrom-Json

if ($null -eq $firebaseConfig.firestore) {
    $firebaseConfig | Add-Member `
        -NotePropertyName 'firestore' `
        -NotePropertyValue ([pscustomobject]@{
            rules = 'firestore.rules'
            indexes = 'firestore.indexes.json'
        })
} else {
    $firebaseConfig.firestore.rules = 'firestore.rules'
    $firebaseConfig.firestore.indexes = 'firestore.indexes.json'
}

$firebaseContent = $firebaseConfig |
    ConvertTo-Json -Depth 20

Write-ProjectFile `
    -RelativePath $firebaseJson `
    -Content ($firebaseContent + "`n")

$formatFiles = @(
    $rolesPage,
    $assignmentRepository,
    $assignmentForm,
    'lib/features/access_control/data/services/access_control_migration_service.dart',
    'lib/features/access_control/presentation/pages/access_control_production_readiness_page.dart'
)

Write-Host ''
Write-Host 'Running dart format...' -ForegroundColor Cyan

& dart format $formatFiles

if ($LASTEXITCODE -ne 0) {
    throw 'dart format failed.'
}

Write-Host ''
Write-Host 'Running flutter analyze...' -ForegroundColor Cyan

& flutter analyze

if ($LASTEXITCODE -ne 0) {
    throw 'flutter analyze found issues. Copy the complete output into ChatGPT.'
}

Write-Host ''
Write-Host 'Roles and Permissions Phase 4 staging completed successfully.' -ForegroundColor Green
Write-Host 'IMPORTANT: Firestore rules were staged but NOT deployed.' -ForegroundColor Yellow
Write-Host 'Run migration and production readiness validation inside the app before deployment.' -ForegroundColor Yellow
Write-Host "Deployment guide: docs/roles_permissions_phase4_production_deployment.md" -ForegroundColor Cyan
Write-Host "Backup: $backupRoot" -ForegroundColor DarkGray
