import '../../domain/entities/document_element_entity.dart';
import '../../domain/entities/document_element_style.dart';
import '../../domain/entities/document_element_type.dart';
import '../../domain/entities/document_page_entity.dart';
import '../../domain/entities/document_template_category.dart';
import '../../domain/entities/document_template_entity.dart';
import '../../domain/entities/document_type.dart';

DocumentTemplateEntity buildMeritCertificateTemplateV1() {
  final now = DateTime.now();

  return DocumentTemplateEntity(
    id: 'merit_certificate_official_v1',
    name: 'Merit Certificate Official',
    documentType: DocumentType.meritCertificate,
    category: DocumentTemplateCategory.official,
    version: 1,
    layoutKey: 'merit_certificate_official',
    description:
        'Official merit certificate for outstanding academic performance.',
    isDefault: true,
    isActive: true,
    useSchoolLogo: true,
    useSchoolName: true,
    usePrincipalName: true,
    usePrincipalDesignation: true,
    usePrincipalSignature: true,
    useSchoolStamp: true,
    createdAt: now,
    updatedAt: now,
    metadata: const <String, dynamic>{
      'theme': 'merit_gold',
      'documentPurpose': 'merit_certificate',
      'paperSize': 'A4',
      'orientation': 'landscape',
    },
    pages: [
      DocumentPageEntity(
        id: 'merit_certificate_page_1',
        width: 1123,
        height: 794,
        orientation: DocumentPageOrientation.landscape,
        backgroundColor: '#FFFFFF',
        pageNumber: 1,
        elements: const [
          DocumentElementEntity(
            id: 'outer_border',
            type: DocumentElementType.shape,
            x: 0.025,
            y: 0.035,
            width: 0.95,
            height: 0.93,
            zIndex: 1,
            style: DocumentElementStyle(
              backgroundColor: '#FFFFFF',
              borderColor: '#B88917',
              borderWidth: 4,
            ),
          ),
          DocumentElementEntity(
            id: 'inner_border',
            type: DocumentElementType.shape,
            x: 0.04,
            y: 0.055,
            width: 0.92,
            height: 0.89,
            zIndex: 2,
            style: DocumentElementStyle(
              backgroundColor: '#FFFFFF',
              borderColor: '#D9B44A',
              borderWidth: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'school_logo',
            type: DocumentElementType.schoolLogo,
            x: 0.075,
            y: 0.09,
            width: 0.12,
            height: 0.13,
            zIndex: 10,
            dataKey: 'branding.schoolLogo',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'school_name',
            type: DocumentElementType.text,
            x: 0.20,
            y: 0.085,
            width: 0.65,
            height: 0.07,
            zIndex: 11,
            staticValue: '{{branding.schoolName}}',
            style: DocumentElementStyle(
              fontSize: 31,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'certificate_title',
            type: DocumentElementType.text,
            x: 0.22,
            y: 0.19,
            width: 0.56,
            height: 0.07,
            zIndex: 12,
            staticValue: 'CERTIFICATE OF MERIT',
            style: DocumentElementStyle(
              fontSize: 28,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#B88917',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              letterSpacing: 1.5,
            ),
          ),
          DocumentElementEntity(
            id: 'presented_to',
            type: DocumentElementType.text,
            x: 0.25,
            y: 0.295,
            width: 0.50,
            height: 0.035,
            zIndex: 13,
            staticValue:
                'This certificate is proudly presented to',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.normal,
              italic: true,
              textColor: '#475467',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'student_name',
            type: DocumentElementType.text,
            x: 0.15,
            y: 0.345,
            width: 0.70,
            height: 0.08,
            zIndex: 14,
            staticValue: '{{student.name}}',
            style: DocumentElementStyle(
              fontSize: 34,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'achievement',
            type: DocumentElementType.text,
            x: 0.12,
            y: 0.45,
            width: 0.76,
            height: 0.15,
            zIndex: 15,
            staticValue:
                'for securing {{merit.position}} position in {{merit.examName}}\n'
                'for Class {{student.classSection}} during Academic Session {{merit.academicSession}}.\n'
                'Percentage: {{merit.percentage}}%     Grade: {{merit.grade}}',
            style: DocumentElementStyle(
              fontSize: 18,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 4,
            ),
          ),
          DocumentElementEntity(
            id: 'commendation',
            type: DocumentElementType.text,
            x: 0.18,
            y: 0.625,
            width: 0.64,
            height: 0.06,
            zIndex: 15,
            staticValue:
                'In recognition of outstanding academic performance and dedication.',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.normal,
              italic: true,
              textColor: '#667085',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'issue_date',
            type: DocumentElementType.text,
            x: 0.09,
            y: 0.78,
            width: 0.24,
            height: 0.04,
            zIndex: 16,
            staticValue: 'Date: {{merit.issueDate}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'school_stamp',
            type: DocumentElementType.schoolStamp,
            x: 0.415,
            y: 0.75,
            width: 0.17,
            height: 0.12,
            zIndex: 20,
            dataKey: 'branding.schoolStamp',
            visibleWhenKey: 'branding.schoolStamp',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_signature',
            type: DocumentElementType.principalSignature,
            x: 0.70,
            y: 0.745,
            width: 0.19,
            height: 0.08,
            zIndex: 20,
            dataKey: 'branding.principalSignature',
            visibleWhenKey: 'branding.principalSignature',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_name',
            type: DocumentElementType.text,
            x: 0.67,
            y: 0.825,
            width: 0.25,
            height: 0.035,
            zIndex: 21,
            staticValue: '{{branding.principalName}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_designation',
            type: DocumentElementType.text,
            x: 0.67,
            y: 0.86,
            width: 0.25,
            height: 0.03,
            zIndex: 21,
            staticValue: '{{branding.principalDesignation}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#667085',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
        ],
      ),
    ],
  );
}
