import '../../domain/entities/document_element_entity.dart';
import '../../domain/entities/document_element_style.dart';
import '../../domain/entities/document_element_type.dart';
import '../../domain/entities/document_page_entity.dart';
import '../../domain/entities/document_template_category.dart';
import '../../domain/entities/document_template_entity.dart';
import '../../domain/entities/document_type.dart';

DocumentTemplateEntity buildFeeReceiptTemplateV1() {
  final now = DateTime.now();

  return DocumentTemplateEntity(
    id: 'fee_receipt_official_v1',
    name: 'Fee Receipt Official',
    documentType: DocumentType.feeReceipt,
    category: DocumentTemplateCategory.official,
    version: 1,
    layoutKey: 'fee_receipt_official',
    description:
        'Official school fee receipt with payment allocations, amount received, advance details and school branding.',
    isDefault: true,
    isActive: true,
    useSchoolLogo: true,
    useSchoolName: true,
    usePrincipalName: false,
    usePrincipalDesignation: false,
    usePrincipalSignature: false,
    useSchoolStamp: true,
    createdAt: now,
    updatedAt: now,
    metadata: const <String, dynamic>{
      'theme': 'official_blue',
      'documentPurpose': 'fee_receipt',
      'paperSize': 'A5',
      'orientation': 'portrait',
    },
    pages: [
      DocumentPageEntity(
        id: 'fee_receipt_page_1',
        width: 559,
        height: 794,
        orientation: DocumentPageOrientation.portrait,
        backgroundColor: '#FFFFFF',
        pageNumber: 1,
        elements: const [
          DocumentElementEntity(
            id: 'outer_border',
            type: DocumentElementType.shape,
            x: 0.035,
            y: 0.025,
            width: 0.93,
            height: 0.95,
            zIndex: 1,
            style: DocumentElementStyle(
              backgroundColor: '#FFFFFF',
              borderColor: '#123A63',
              borderWidth: 3,
            ),
          ),
          DocumentElementEntity(
            id: 'header_background',
            type: DocumentElementType.shape,
            x: 0.035,
            y: 0.025,
            width: 0.93,
            height: 0.15,
            zIndex: 2,
            style: DocumentElementStyle(
              backgroundColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'school_logo',
            type: DocumentElementType.schoolLogo,
            x: 0.07,
            y: 0.055,
            width: 0.16,
            height: 0.09,
            zIndex: 10,
            dataKey: 'branding.schoolLogo',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'school_name',
            type: DocumentElementType.text,
            x: 0.25,
            y: 0.05,
            width: 0.65,
            height: 0.065,
            zIndex: 11,
            staticValue: '{{branding.schoolName}}',
            style: DocumentElementStyle(
              fontSize: 23,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#FFFFFF',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'receipt_title',
            type: DocumentElementType.text,
            x: 0.27,
            y: 0.115,
            width: 0.60,
            height: 0.035,
            zIndex: 11,
            staticValue: 'FEE RECEIPT',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#D9EAF7',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              letterSpacing: 1.0,
            ),
          ),
          DocumentElementEntity(
            id: 'receipt_number',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.205,
            width: 0.44,
            height: 0.035,
            zIndex: 12,
            staticValue:
                'Receipt No: {{receipt.number}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'receipt_date',
            type: DocumentElementType.text,
            x: 0.55,
            y: 0.205,
            width: 0.37,
            height: 0.035,
            zIndex: 12,
            staticValue:
                'Date: {{receipt.paymentDate}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.right,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'student_name',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.265,
            width: 0.84,
            height: 0.04,
            zIndex: 13,
            staticValue:
                'Student: {{student.name}}',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'admission_no',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.31,
            width: 0.42,
            height: 0.035,
            zIndex: 13,
            staticValue:
                'Admission No: {{student.admissionNo}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'class_section',
            type: DocumentElementType.text,
            x: 0.52,
            y: 0.31,
            width: 0.40,
            height: 0.035,
            zIndex: 13,
            staticValue:
                'Class: {{student.classSection}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.right,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'session',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.35,
            width: 0.84,
            height: 0.035,
            zIndex: 13,
            staticValue:
                'Academic Session: {{receipt.academicSession}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'allocation_header',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.41,
            width: 0.84,
            height: 0.04,
            zIndex: 14,
            staticValue: 'PAYMENT DETAILS',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#FFFFFF',
              backgroundColor: '#123A63',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'allocation_lines',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.46,
            width: 0.84,
            height: 0.15,
            zIndex: 14,
            staticValue: '{{receipt.allocationLines}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.top,
              maxLines: 8,
            ),
          ),
          DocumentElementEntity(
            id: 'payment_method',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.62,
            width: 0.84,
            height: 0.035,
            zIndex: 15,
            staticValue:
                'Payment Method: {{receipt.paymentMethod}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'reference',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.66,
            width: 0.84,
            height: 0.035,
            zIndex: 15,
            staticValue:
                'Reference / Transaction No: {{receipt.referenceNumber}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'amount_summary',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.715,
            width: 0.84,
            height: 0.105,
            zIndex: 16,
            staticValue:
                'Amount Received: Rs. {{receipt.totalPaid}}\n'
                'Advance Used: Rs. {{receipt.advanceUsed}}     Advance Created: Rs. {{receipt.advanceAmount}}\n'
                'Total Applied: Rs. {{receipt.totalApplied}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 4,
            ),
          ),
          DocumentElementEntity(
            id: 'amount_words',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.825,
            width: 0.84,
            height: 0.05,
            zIndex: 16,
            staticValue:
                'Amount in Words: {{receipt.amountInWords}}',
            style: DocumentElementStyle(
              fontSize: 10,
              fontWeight: DocumentFontWeight.normal,
              italic: true,
              textColor: '#475467',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'notes',
            type: DocumentElementType.text,
            x: 0.08,
            y: 0.875,
            width: 0.52,
            height: 0.045,
            zIndex: 17,
            staticValue:
                'Notes: {{receipt.notes}}',
            style: DocumentElementStyle(
              fontSize: 9,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#667085',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'school_stamp',
            type: DocumentElementType.schoolStamp,
            x: 0.10,
            y: 0.91,
            width: 0.17,
            height: 0.055,
            zIndex: 20,
            dataKey: 'branding.schoolStamp',
            visibleWhenKey: 'branding.schoolStamp',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'accounts_signature',
            type: DocumentElementType.text,
            x: 0.65,
            y: 0.925,
            width: 0.25,
            height: 0.025,
            zIndex: 20,
            staticValue: 'Accounts Signature',
            style: DocumentElementStyle(
              fontSize: 10,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#475467',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'footer_note',
            type: DocumentElementType.text,
            x: 0.30,
            y: 0.95,
            width: 0.40,
            height: 0.02,
            zIndex: 21,
            staticValue:
                'Thank you for your payment.',
            style: DocumentElementStyle(
              fontSize: 9,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#667085',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
        ],
      ),
    ],
  );
}
