import '../../domain/entities/document_element_entity.dart';
import '../../domain/entities/document_element_style.dart';
import '../../domain/entities/document_element_type.dart';
import '../../domain/entities/document_page_entity.dart';
import '../../domain/entities/document_template_category.dart';
import '../../domain/entities/document_template_entity.dart';
import '../../domain/entities/document_type.dart';

DocumentTemplateEntity buildExperienceCertificateTemplateV1() {
  final now = DateTime.now();

  return DocumentTemplateEntity(
    id: 'experience_certificate_official_v1',
    name: 'Experience Certificate Official',
    documentType: DocumentType.experienceCertificate,
    category: DocumentTemplateCategory.official,
    version: 1,
    layoutKey: 'experience_certificate_official',
    description:
        'Official staff experience certificate generated from manual Document Center input.',
    isDefault: true,
    isActive: true,
    useSchoolLogo: true,
    useSchoolName: true,
    usePrincipalName: true,
    usePrincipalDesignation: true,
    usePrincipalSignature: true,
    useSchoolStamp: true,
    createdAt: now,
    updatedAt: now,
    metadata: const <String, dynamic>{
      'theme': 'official_blue',
      'documentPurpose': 'experience_certificate',
      'paperSize': 'A4',
      'orientation': 'portrait',
    },
    pages: [
      DocumentPageEntity(
        id: 'experience_certificate_page_1',
        width: 794,
        height: 1123,
        orientation: DocumentPageOrientation.portrait,
        backgroundColor: '#FFFFFF',
        pageNumber: 1,
        elements: const [
          DocumentElementEntity(
            id: 'outer_border',
            type: DocumentElementType.shape,
            x: 0.035,
            y: 0.025,
            width: 0.93,
            height: 0.95,
            zIndex: 1,
            style: DocumentElementStyle(
              backgroundColor: '#FFFFFF',
              borderColor: '#123A63',
              borderWidth: 3,
            ),
          ),
          DocumentElementEntity(
            id: 'header',
            type: DocumentElementType.shape,
            x: 0.05,
            y: 0.045,
            width: 0.90,
            height: 0.145,
            zIndex: 2,
            style: DocumentElementStyle(
              backgroundColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'school_logo',
            type: DocumentElementType.schoolLogo,
            x: 0.075,
            y: 0.07,
            width: 0.13,
            height: 0.09,
            zIndex: 10,
            dataKey: 'branding.schoolLogo',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'school_name',
            type: DocumentElementType.text,
            x: 0.22,
            y: 0.065,
            width: 0.65,
            height: 0.07,
            zIndex: 11,
            staticValue: '{{branding.schoolName}}',
            style: DocumentElementStyle(
              fontSize: 29,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#FFFFFF',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'title',
            type: DocumentElementType.text,
            x: 0.25,
            y: 0.135,
            width: 0.60,
            height: 0.035,
            zIndex: 11,
            staticValue: 'EXPERIENCE CERTIFICATE',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#D9EAF7',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              letterSpacing: 1.1,
            ),
          ),
          DocumentElementEntity(
            id: 'issue_date',
            type: DocumentElementType.text,
            x: 0.66,
            y: 0.225,
            width: 0.24,
            height: 0.035,
            zIndex: 12,
            staticValue: 'Date: {{experience.issueDate}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.right,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'to_whom',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.31,
            width: 0.80,
            height: 0.05,
            zIndex: 12,
            staticValue: 'TO WHOM IT MAY CONCERN',
            style: DocumentElementStyle(
              fontSize: 18,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'body_1',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.405,
            width: 0.80,
            height: 0.13,
            zIndex: 13,
            staticValue:
                'This is to certify that {{experience.employeeName}} worked with {{branding.schoolName}} as {{experience.designation}} from {{experience.joiningDate}} to {{experience.leavingDate}}.',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.justify,
              verticalAlignment: DocumentVerticalAlignment.top,
              maxLines: 6,
            ),
          ),
          DocumentElementEntity(
            id: 'body_2',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.555,
            width: 0.80,
            height: 0.12,
            zIndex: 13,
            staticValue:
                'During the period of service, the employee performed assigned duties with responsibility, dedication and professionalism.',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.justify,
              verticalAlignment: DocumentVerticalAlignment.top,
              maxLines: 5,
            ),
          ),
          DocumentElementEntity(
            id: 'remarks',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.69,
            width: 0.80,
            height: 0.10,
            zIndex: 13,
            staticValue: '{{experience.remarks}}',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.normal,
              italic: true,
              textColor: '#475467',
              textAlignment: DocumentTextAlignment.justify,
              verticalAlignment: DocumentVerticalAlignment.top,
              maxLines: 5,
            ),
          ),
          DocumentElementEntity(
            id: 'closing',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.805,
            width: 0.80,
            height: 0.05,
            zIndex: 14,
            staticValue:
                'We wish {{experience.employeeName}} every success in future endeavors.',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.left,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'school_stamp',
            type: DocumentElementType.schoolStamp,
            x: 0.12,
            y: 0.875,
            width: 0.17,
            height: 0.07,
            zIndex: 20,
            dataKey: 'branding.schoolStamp',
            visibleWhenKey: 'branding.schoolStamp',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_signature',
            type: DocumentElementType.principalSignature,
            x: 0.68,
            y: 0.855,
            width: 0.18,
            height: 0.07,
            zIndex: 20,
            dataKey: 'branding.principalSignature',
            visibleWhenKey: 'branding.principalSignature',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_name',
            type: DocumentElementType.text,
            x: 0.64,
            y: 0.925,
            width: 0.26,
            height: 0.025,
            zIndex: 21,
            staticValue: '{{branding.principalName}}',
            style: DocumentElementStyle(
              fontSize: 11,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_designation',
            type: DocumentElementType.text,
            x: 0.64,
            y: 0.95,
            width: 0.26,
            height: 0.02,
            zIndex: 21,
            staticValue: '{{branding.principalDesignation}}',
            style: DocumentElementStyle(
              fontSize: 10,
              fontWeight: DocumentFontWeight.normal,
              textColor: '#667085',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
        ],
      ),
    ],
  );
}
