import '../../domain/entities/document_element_entity.dart';
import '../../domain/entities/document_element_style.dart';
import '../../domain/entities/document_element_type.dart';
import '../../domain/entities/document_page_entity.dart';
import '../../domain/entities/document_template_category.dart';
import '../../domain/entities/document_template_entity.dart';
import '../../domain/entities/document_type.dart';

DocumentTemplateEntity buildSalarySlipTemplateV1() {
  final now = DateTime.now();

  return DocumentTemplateEntity(
    id: 'salary_slip_official_v1',
    name: 'Salary Slip Official',
    documentType: DocumentType.salarySlip,
    category: DocumentTemplateCategory.official,
    version: 1,
    layoutKey: 'salary_slip_official',
    description: 'Official monthly employee salary slip.',
    isDefault: true,
    isActive: true,
    useSchoolLogo: true,
    useSchoolName: true,
    usePrincipalName: true,
    usePrincipalDesignation: true,
    usePrincipalSignature: true,
    useSchoolStamp: true,
    createdAt: now,
    updatedAt: now,
    metadata: const <String, dynamic>{
      'theme': 'official_blue',
      'documentPurpose': 'salary_slip',
      'paperSize': 'A4',
      'orientation': 'portrait',
    },
    pages: [
      DocumentPageEntity(
        id: 'salary_slip_page_1',
        width: 794,
        height: 1123,
        orientation: DocumentPageOrientation.portrait,
        backgroundColor: '#FFFFFF',
        pageNumber: 1,
        elements: const [
          DocumentElementEntity(
            id: 'outer_border',
            type: DocumentElementType.shape,
            x: 0.04,
            y: 0.035,
            width: 0.92,
            height: 0.92,
            zIndex: 1,
            style: DocumentElementStyle(
              backgroundColor: '#FFFFFF',
              borderColor: '#123A63',
              borderWidth: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'header',
            type: DocumentElementType.shape,
            x: 0.04,
            y: 0.035,
            width: 0.92,
            height: 0.15,
            zIndex: 2,
            style: DocumentElementStyle(
              backgroundColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'school_logo',
            type: DocumentElementType.schoolLogo,
            x: 0.075,
            y: 0.06,
            width: 0.13,
            height: 0.09,
            zIndex: 10,
            dataKey: 'branding.schoolLogo',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'school_name',
            type: DocumentElementType.text,
            x: 0.22,
            y: 0.055,
            width: 0.66,
            height: 0.07,
            zIndex: 11,
            staticValue: '{{branding.schoolName}}',
            style: DocumentElementStyle(
              fontSize: 28,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#FFFFFF',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              maxLines: 2,
            ),
          ),
          DocumentElementEntity(
            id: 'title',
            type: DocumentElementType.text,
            x: 0.30,
            y: 0.125,
            width: 0.50,
            height: 0.035,
            zIndex: 11,
            staticValue: 'SALARY SLIP',
            style: DocumentElementStyle(
              fontSize: 16,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#D9EAF7',
              textAlignment: DocumentTextAlignment.center,
              verticalAlignment: DocumentVerticalAlignment.center,
              letterSpacing: 1.2,
            ),
          ),
          DocumentElementEntity(
            id: 'month',
            type: DocumentElementType.text,
            x: 0.60,
            y: 0.21,
            width: 0.28,
            height: 0.035,
            zIndex: 12,
            staticValue: 'Salary Month: {{salary.month}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.right,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'employee_name',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.275,
            width: 0.45,
            height: 0.04,
            zIndex: 12,
            staticValue: 'Employee: {{salary.staffName}}',
            style: DocumentElementStyle(
              fontSize: 14,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'employee_id',
            type: DocumentElementType.text,
            x: 0.56,
            y: 0.275,
            width: 0.32,
            height: 0.04,
            zIndex: 12,
            staticValue: 'Employee ID: {{salary.staffCode}}',
            style: DocumentElementStyle(
              fontSize: 13,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.right,
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),
          DocumentElementEntity(
            id: 'designation',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.32,
            width: 0.50,
            height: 0.04,
            zIndex: 12,
            staticValue: 'Designation: {{salary.designation}}',
            style: DocumentElementStyle(
              fontSize: 13,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              verticalAlignment: DocumentVerticalAlignment.center,
            ),
          ),

          DocumentElementEntity(
            id: 'earnings_header',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.405,
            width: 0.35,
            height: 0.04,
            zIndex: 13,
            staticValue: 'EARNINGS',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'basic_salary',
            type: DocumentElementType.text,
            x: 0.12,
            y: 0.455,
            width: 0.38,
            height: 0.04,
            zIndex: 13,
            staticValue: 'Basic Salary: Rs. {{salary.basicSalary}}',
            style: DocumentElementStyle(
              fontSize: 13,
              textColor: '#344054',
            ),
          ),
          DocumentElementEntity(
            id: 'allowance',
            type: DocumentElementType.text,
            x: 0.12,
            y: 0.50,
            width: 0.38,
            height: 0.04,
            zIndex: 13,
            staticValue: 'Allowance: Rs. {{salary.allowance}}',
            style: DocumentElementStyle(
              fontSize: 13,
              textColor: '#344054',
            ),
          ),
          DocumentElementEntity(
            id: 'gross',
            type: DocumentElementType.text,
            x: 0.12,
            y: 0.545,
            width: 0.38,
            height: 0.04,
            zIndex: 13,
            staticValue: 'Gross Salary: Rs. {{salary.grossSalary}}',
            style: DocumentElementStyle(
              fontSize: 13,
              fontWeight: DocumentFontWeight.semiBold,
              textColor: '#182230',
            ),
          ),

          DocumentElementEntity(
            id: 'deductions_header',
            type: DocumentElementType.text,
            x: 0.54,
            y: 0.405,
            width: 0.32,
            height: 0.04,
            zIndex: 13,
            staticValue: 'DEDUCTIONS',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'deduction',
            type: DocumentElementType.text,
            x: 0.56,
            y: 0.455,
            width: 0.32,
            height: 0.04,
            zIndex: 13,
            staticValue: 'Other: Rs. {{salary.deduction}}',
            style: DocumentElementStyle(
              fontSize: 13,
              textColor: '#344054',
            ),
          ),
          DocumentElementEntity(
            id: 'attendance_deduction',
            type: DocumentElementType.text,
            x: 0.56,
            y: 0.50,
            width: 0.32,
            height: 0.04,
            zIndex: 13,
            staticValue:
                'Attendance: Rs. {{salary.attendanceDeduction}}',
            style: DocumentElementStyle(
              fontSize: 13,
              textColor: '#344054',
            ),
          ),

          DocumentElementEntity(
            id: 'attendance_header',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.63,
            width: 0.78,
            height: 0.04,
            zIndex: 13,
            staticValue: 'ATTENDANCE SUMMARY',
            style: DocumentElementStyle(
              fontSize: 15,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
            ),
          ),
          DocumentElementEntity(
            id: 'attendance_summary',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.685,
            width: 0.78,
            height: 0.05,
            zIndex: 13,
            staticValue:
                'Present: {{salary.presentDays}}   |   Absent: {{salary.absentDays}}   |   Late: {{salary.lateDays}}   |   Leave: {{salary.leaveDays}}',
            style: DocumentElementStyle(
              fontSize: 13,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.center,
            ),
          ),

          DocumentElementEntity(
            id: 'net_salary_box',
            type: DocumentElementType.shape,
            x: 0.10,
            y: 0.765,
            width: 0.78,
            height: 0.08,
            zIndex: 12,
            style: DocumentElementStyle(
              backgroundColor: '#EEF5FC',
              borderColor: '#123A63',
              borderWidth: 1,
            ),
          ),
          DocumentElementEntity(
            id: 'net_salary',
            type: DocumentElementType.text,
            x: 0.15,
            y: 0.785,
            width: 0.68,
            height: 0.04,
            zIndex: 15,
            staticValue: 'NET SALARY: Rs. {{salary.netSalary}}',
            style: DocumentElementStyle(
              fontSize: 19,
              fontWeight: DocumentFontWeight.bold,
              textColor: '#123A63',
              textAlignment: DocumentTextAlignment.center,
            ),
          ),

          DocumentElementEntity(
            id: 'payment_status',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.865,
            width: 0.40,
            height: 0.035,
            zIndex: 15,
            staticValue: 'Payment Status: {{salary.paymentStatus}}',
            style: DocumentElementStyle(
              fontSize: 12,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
            ),
          ),
          DocumentElementEntity(
            id: 'payment_details',
            type: DocumentElementType.text,
            x: 0.10,
            y: 0.905,
            width: 0.52,
            height: 0.035,
            zIndex: 15,
            staticValue:
                'Payment: {{salary.paymentMethod}}  {{salary.paymentReference}}',
            style: DocumentElementStyle(
              fontSize: 11,
              textColor: '#667085',
            ),
          ),
          DocumentElementEntity(
            id: 'principal_signature',
            type: DocumentElementType.principalSignature,
            x: 0.68,
            y: 0.865,
            width: 0.18,
            height: 0.055,
            zIndex: 20,
            dataKey: 'branding.principalSignature',
            visibleWhenKey: 'branding.principalSignature',
            visibleWhenValue: 'exists',
            style: DocumentElementStyle(
              imageFit: DocumentImageFit.contain,
            ),
          ),
          DocumentElementEntity(
            id: 'principal_label',
            type: DocumentElementType.text,
            x: 0.67,
            y: 0.925,
            width: 0.20,
            height: 0.025,
            zIndex: 21,
            staticValue: 'Authorized Signature',
            style: DocumentElementStyle(
              fontSize: 10,
              fontWeight: DocumentFontWeight.medium,
              textColor: '#344054',
              textAlignment: DocumentTextAlignment.center,
            ),
          ),
        ],
      ),
    ],
  );
}
