import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/di/service_locator.dart';
import '../../domain/entities/exam_entity.dart';
import '../../domain/repositories/exam_repository.dart';
import '../bloc/exam_bloc.dart';
import 'marks_entry_page.dart';

class ExamsPage extends StatelessWidget { const ExamsPage({super.key}); @override Widget build(BuildContext context) => BlocProvider(create: (_) => sl<ExamBloc>()..add(const LoadExams()), child: const _ExamsView()); }
class _ExamsView extends StatefulWidget { const _ExamsView(); @override State<_ExamsView> createState() => _ExamsViewState(); }
class _ExamsViewState extends State<_ExamsView> { final _name=TextEditingController(); final _class=TextEditingController(); final _section=TextEditingController(); final _subject=TextEditingController(); ExamType _type=ExamType.monthly; @override void dispose(){_name.dispose();_class.dispose();_section.dispose();_subject.dispose();super.dispose();} void _save(){if([_name,_class,_section,_subject].any((c)=>c.text.trim().isEmpty))return;final repo=sl<ExamRepository>();context.read<ExamBloc>().add(SaveExam(ExamEntity(id:repo.generateId(),name:_name.text.trim(),type:_type,academicSession:'${DateTime.now().year}-${DateTime.now().year+1}',classId:_class.text.trim(),sectionId:_section.text.trim(),subject:_subject.text.trim(),examDate:DateTime.now(),totalMarks:100,passingMarks:33,createdAt:DateTime.now())));}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Examinations')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:_name,decoration:const InputDecoration(labelText:'Exam Name')),TextField(controller:_class,decoration:const InputDecoration(labelText:'Class')),TextField(controller:_section,decoration:const InputDecoration(labelText:'Section')),TextField(controller:_subject,decoration:const InputDecoration(labelText:'Subject')),DropdownButton<ExamType>(value:_type,items:ExamType.values.map((v)=>DropdownMenuItem(value:v,child:Text(v.name))).toList(),onChanged:(v)=>setState(()=>_type=v??_type)),FilledButton(onPressed:_save,child:const Text('Save Exam'))]))),const SizedBox(height:12),Expanded(child:BlocBuilder<ExamBloc,ExamState>(builder:(context,state){final exams=state is ExamLoaded?state.exams:<ExamEntity>[];return ListView.builder(itemCount:exams.length,itemBuilder:(context,index){final exam=exams[index];return Card(child:ListTile(title:Text(exam.name),subtitle:Text('${exam.subject} • ${exam.classId}-${exam.sectionId}'),trailing:FilledButton(onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>MarksEntryPage(exam:exam))),child:const Text('Marks'))));});}))])));}
