import 'package:flutter/material.dart';
import '../../../../core/di/service_locator.dart';
import '../../../../core/services/firebase_firestore_service.dart';
import '../../../students/domain/entities/student_entity.dart';
import '../../../students/domain/repositories/student_repository.dart';
import '../../data/datasources/exam_mark_remote_datasource.dart';
import '../../data/models/exam_mark_model.dart';
import '../../domain/entities/exam_entity.dart';
import '../../domain/entities/exam_mark_entity.dart';

class MarksEntryPage extends StatefulWidget { const MarksEntryPage({super.key, required this.exam}); final ExamEntity exam; @override State<MarksEntryPage> createState()=>_MarksEntryPageState(); }
class _MarksEntryPageState extends State<MarksEntryPage> { late final Future<List<StudentEntity>> _students=sl<StudentRepository>().getStudents(); final Map<String,TextEditingController> _marks={}; final Set<String> _absent={}; bool _saving=false; @override void dispose(){for(final c in _marks.values){c.dispose();}super.dispose();}
  Future<void> _save(List<StudentEntity> students) async { setState(()=>_saving=true); final source=ExamMarkRemoteDataSource(firestoreService:sl<FirebaseFirestoreService>()); try{for(final student in students){final absent=_absent.contains(student.id);final mark=absent?0.0:double.tryParse(_marks[student.id]?.text.trim()??'');if(mark==null||mark<0||mark>widget.exam.totalMarks)throw StateError('Enter valid marks for ${student.fullName}.');await source.save(ExamMarkModel.fromEntity(ExamMarkEntity(id:'${widget.exam.id}_${student.id}',examId:widget.exam.id,studentId:student.id,studentName:student.fullName,admissionNo:student.admissionNo,obtainedMarks:mark,isAbsent:absent,updatedAt:DateTime.now())));}if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Marks saved successfully.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>_saving=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('${widget.exam.name} Marks Entry')),body:FutureBuilder<List<StudentEntity>>(future:_students,builder:(context,snapshot){if(!snapshot.hasData)return const Center(child:CircularProgressIndicator());final students=snapshot.data!.where((s)=>s.classId==widget.exam.classId&&s.sectionId==widget.exam.sectionId).toList()..sort((a,b)=>int.tryParse(a.rollNumber)?.compareTo(int.tryParse(b.rollNumber)??0)??a.rollNumber.compareTo(b.rollNumber));return Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:students.length,itemBuilder:(context,index){final student=students[index];final controller=_marks.putIfAbsent(student.id,TextEditingController.new);final absent=_absent.contains(student.id);return Card(child:ListTile(title:Text(student.fullName),subtitle:Text('Roll: ${student.rollNumber} • ${student.admissionNo}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[SizedBox(width:105,child:TextField(controller:controller,enabled:!absent,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'/${widget.exam.totalMarks}',border:const OutlineInputBorder()))),Checkbox(value:absent,onChanged:(v)=>setState((){if(v==true){_absent.add(student.id);controller.clear();}else{_absent.remove(student.id);}}))])));})),Padding(padding:const EdgeInsets.all(16),child:SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:_saving?null:()=>_save(students),icon:const Icon(Icons.save),label:Text(_saving?'Saving...':'Save Marks'))))]);}));}
